<section class="page-title" 
style="background-image: url(<?php echo BASE_URL; ?>/public/images/au2signBanner2.jpg); height: 200px;">    
</section>

<section class="services-section style-two">
    <div class="auto-container">
        <div class="row">

            <div class="image-column col-lg-7 col-md-12 col-sm-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/procesoMultidisciplinario.jpg);"></div>
            <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                <div class="inner-column">            
                    <div class="sec-title">
                        <h3>
                            Proceso Multidisciplinario
                        </h3>
                        <div class="text">
                            <strong>
                            Cuando hablamos de la firma digital de un contrato ya no solamente estamos hablando del impacto que conlleva para el área jurídica, ya es una tarea de distintas áreas:
                            </strong>
                        </div>
                    </div>
                    <ul class="list-style-one">
                        <li>
                            El equipo laboral necesita ser más eficiente en el trato con los colaboradores, generar ahorros y ofrecer una mejor experiencia a los involucrados.
                        </li>
                        <li>
                            El equipo laboral necesita firmar de nuevo los contratos laborales para permitir una libre afiliación a un Sindicado a los trabajadores.
                        </li>
                        <li>El equipo comercial necesita vender más por lo que necesita ser más eficiente de cara a los cierres.</li>
                        <li>
                            El equipo de compras quiere tener firmados más rápidamente los contratos que mandan a sus proveedores, localizarlos más rápido y dar una una mejor experiencia a las partes.
                        </li>
                        <li>
                            El equipo fiscal quiere que exista un contrato firmado digital con su respectiva NOM 151 y estampilla de tiempo para tener una fecha cierta sobre el documento.
                        </li>
                    </ul>
                    
                    <a href="<?php echo BASE_URL; ?>contacto" class="theme-btn icon-btn-two">
                        <span>Contactar</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="fluid-section-four">
    <div class="auto-container">
        <div class="row">
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <h3>
                        Servicio Sincróno  
                        </h3>
                        <div class="text">
                            En este servicio esperamos los bytes del documento, 
                            la(s) firma(s) digitalizada(s) recopilada(s) por su 
                            front, las coordenadas de las firmas así como el nombre, 
                            apellidos del firmante y correo, y podrán recuperar tanto
                            el PDF firmadoc con un certificado de identidad detrás 
                            de la firma así como la NOM 151 con su respectiva estampilla
                            de tiempo.
                        </div>
                    </div>
                </div>
            </div>

            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12">
                <div class="image-layer" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/18.jpg);"></div>
            </div>
        </div>
    </div>
</section>

<section class="fluid-section-two">
    <div class="container-fluid">
        <div class="row no-gutters">
            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/marcoRegulatorio.jpg);"></div>

            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <!-- <span class="sub-title">innovations</span> -->
                        <h3>
                            Cumplimos con el<br>
                            Marco Regulatorio
                        </h3>
                        <ul class="list-style-one">
                            <li>
                                Ley de Firma Electrónica Avanzada. 
                            </li>
                            <li>
                                Código de Comercio.
                            </li>
                            <li>Código Federal de Procedimientos Civiles.</li>
                            <li>Código Civil Federal.</li>
                            <li>Ley Federal del Trabajo (Art. 776 y 836a, 836b y 836c).</li>
                            <li>Ley Federal de transparencia y acceso a la información pública gubernamental.</li>
                            <li>Ley Fintech</li>
                            <li>Decreto por el que se reforma el artículo 199 de la Ley del Mercado de Valores</li>
                            <li>Disposiciones de Carácter General aplicables de las casas de bolsa</li>
                            <li>Disposiciones de Carácter General aplicables a los fondos de inversión y alas personas que les prestan servicios</li>
                            <li>Secretaría de Educación Pública</li>
                            <li>Entre otras...</li>
                        </ul>
                    </div>
                </div>
            </div>  
        </div>
    </div>
</section>

<section class="fluid-section-four">
    <div class="auto-container">
        <div class="row">
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <h3>
                            Cumplimiento internacional
                        </h3>
                        <div class="text">
                            Au2sign cumple con Normativas de carácter internacional y en los diversos sectores de aplicación para el uso de la firma electrónica. Dichos cumplimientos son con base en el siguiente marco normativo. 
                        </div>
                    </div>
                    <a href="<?php echo BASE_URL; ?>cumplimientoInternacional" class="theme-btn icon-btn-two">
                        <span>Ver más</span>
                    </a>
                </div>
            </div>

            <div class="image-column col-lg-6 col-md-12">
                <div class="image-layer" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/cumplimientoInternacional.jpg);"></div>
            </div>
            
        </div>
    </div>
</section>

<!-- <section class="services-section style-two">
    <div class="auto-container">
        <div class="row">
            <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                <div class="inner-column">            
                    <div class="sec-title">
                        <span class="sub-title">Contratos inteligentes</span>
                        <h3>
                            Autosign
                        </h3>
                        <div class="text">
                            <strong>
                                Un contrato inteligente (Smart contract), es un programa informático que permite ejecutar acuerdos registrados entre dos o más partes, es el testigo que ante cierto resultado ejecutará de forma automática ciertas reglas o acciones predefinidas.
                            </strong>
                        </div>
                    </div>
                    <p>
                        Es un programa no controlado por las partes o sus agentes y que ejecuta un contrato automático, el cual funciona como una sentencia if-then (si-entonces) de cualquier otro programa de ordenador. <br><br>
                        Con la diferencia de que se realiza de una manera que interactúa con activos reales.
                    </p>
                    
                    <a href="<?php echo BASE_URL; ?>contacto" class="theme-btn icon-btn-two">
                        <span>Contactar</span>
                    </a>
                </div>
            </div>

            <div class="image-column col-lg-7 col-md-12 col-sm-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/womanComputer.jpg);"></div>           
        </div>
    </div>
</section> -->
