<section class="contact-form-section">
    <div class="auto-container">
        <div class="row form-outer">
            <!-- Image Column -->
            <div class="image-column col-lg-6 col-md-12 col-sm-12">
                <div class="layer-image" style="background-image: url(<?php echo BASE_URL; ?>public/images/certificatePSC.jpg);"></div>
            </div>

            
            <div class="form-column col-lg-6 col-md-12 col-sm-12">
                <div class="default-form contact-form">
                    <div class="title">
                        <h4>Firma Electrónica <br> Avanzada (FEA)</h4>
                        <p>
                            Una firma electrónica de este tipo usa un certificado digital de identidad que va ligado a un firmante y más aún que nace de un proceso enrolamiento, lo que en consecuencia da mayor certeza de la identidad del firmante.
                            <br><br>
                            En este tipo de firmas existen elementos técnicos, jurídicos y operativos que permiten tener un mayor blindaje normativo y por ende aceptación plena ante las autoridades competentes.
                            <br><br>
                            En México hay dos Firmas Electrónicas Avanzadas comúnmente usadas; una es la FIEL(eFirma) que emite el SAT, y la otra los Certificados Emitidos por los PSC (Prestadores de Servicios de Certificación autorizados por la Secretaría de Economía). 
                            <br><br>
                            En la Unión Europea se le llama Firma Electrónica Cualificada o bien firma electrónica reconocida. 

                        </p>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</section>