<section class="contact-form-section">
    <div class="auto-container">
        <div class="row form-outer">
            <!-- Image Column -->
            <div class="image-column col-lg-6 col-md-12 col-sm-12">
                <div class="layer-image" style="background-image: url(<?php echo BASE_URL; ?>public/images/vertorSSL.jpg);"></div>
            </div>

            
            <div class="form-column col-lg-6 col-md-12 col-sm-12">
                <div class="default-form contact-form">
                    <div class="title">
                        <h4>Certificados SSL</h4>
                        <p>
                            Es un titulo digital que 
                            <b>autentica la identidad de un sitio web  </b>
                            y cifra con tecnologia SSL (Secure Sockets Layer) la información que se envía al servidor.
                            <br><br>
                            Este protocolo logra que la transmisión 
                            de datos entre un servidor y un usuario a 
                            través de internet, sea completamente 
                            segura y <b> asegurando la protección de datos 
                            personales </b> o sigilosos que circulan en la web.
                            <br><br>
                            PSC World ofrece 2 tipos de certificados: 
                            <b>Rapid SSL y True BusinesslD </b> (para un solo dominio).
                        </p>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</section>

<section class="pricing-section">
    <div class="auto-container">
        <div class="sec-title text-center">
            <h3>RapidSSL</h3>
            <div class="text">
                Lista de los servicios de RapidSSL que ofrece PSC World
                <br> dentro de su paquete de Certificados SSL.
            </div>
        </div>

        <div class="row clearfix">
            <!-- Pricing Table -->
            <div class="pricing-table col-lg-6 col-md-6 col-sm-12">
                <div class="inner-box">
                    <div class="table-header">
                        <div class="title">Necesidades</div>
                    </div>
                    <div class="table-content">
                        <ul>
                            <li>Dominios asegurado </li>
                            <li>Opciones de vigencia </li>
                            <li>Tiempo de autorización (promedio)</li>
                            <li>
                                Método de Autenticación: Antes de que una Autoridad de
                            Certificación emita un Certificedo SSL, ellos autentican 
                            la información suministrada en Ia solicitud del Certificado 
                            Cuanto más completa sea La Autenticación, habrá más visitantes
                            del sitio que confien en ese Certificado 
                            </li>
                            <li>Validación </li>
                            <li>Cifrado </li>
                            <li>Escaneo de Malware del sitio web </li>
                            <li>Sello de Sitio Confable </li>
                            <li>Compatibilidad con dispositivos móviles </li>
                            <li>
                                Seguro: Es otorgado por el fabricante (puede cambiar en 
                                cualquier momento). En el remoto caso que se llegase a 
                                tener una situación de efectuar algún reclamo este 
                                debe hacerse directamente con el fabricante. 
                            </li>
                            <li>Autoridad Certificadora</li>
                            <li>
                                Compatibilidad con los diferentes navegadores 
                            </li>
                            <li>Proceso de renovación del Certificado</li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Pricing Table -->
            <div class="pricing-table tagged col-lg-6 col-md-6 col-sm-12">
                <div class="inner-box">
                    <div class="table-header">
                        <div class="title">Básico (asegura sitios Web, intranets y extranets)</div>
                    </div>
                    <div class="table-content">
                        <ul>
                            <li>Uno</li>
                            <li>1 a 5 años </li>
                            <li>   
                                Unos minutos después de La instalación, podrá abrir
                                un navegador y buscar el candado cerrado que indica que el 
                                Certificado SSL ahora protege su sitio. 
                            </li>
                            <li>Validación del dominio</li>
                            <li>
                                Automatizada del nombre del dominio. 
                            </li>
                            <li>
                                El cifrado de hasta 256-bit protege las transacciones e 
                                información confidencial durante su transmisión 
                            </li>
                            <li>No</li>
                            <li>
                                De GeoTrust, dinámico, muestra sello de fecha y hora. 
                                Cuando los usuarios de los servicios del dominio en linea o 
                                móviles ven ese sello, saben que su dominio ha sido 
                                verifcado y que su información esta cifrada durante transmisión.
                            </li>
                            <li>Si</li>
                            <li>USD 10.000 </li>
                            <li>Raiz de 2048-bit </li>
                            <li>Si</li>
                            <li>Sin costo</li>
                        </ul>
                    </div>
                </div>
            </div>

            
        </div>
    </div>
</section>