<section class="services-section-two" style="padding: 55px 0 60px;">
    <div class="auto-container">
        
            <div class="sec-title text-center">
                <!-- <span class="icon flaticon-satchel"></span> -->
                <h3>Potente conjunto de caracteristicas</h3>
            </div>


        <div class="row">
            <!-- Service Block -->
            <div class="service-block-two col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <span class="icon flaticon-calendar"></span>
                    <h3><a href="#">Fecha y Hora exacta</a></h3>
                    <div class="text">
                        Permite conocer la fecha y hora exacta de una operación electrónica dentro de un sistema informático, permitiendo la restreabilidad y la validación de integridad del documento o archivo electrónico
                    </div>
                </div>
            </div>

            <!-- Service Block -->
            <div class="service-block-two col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <span class="icon flaticon-patent"></span>
                    <h3><a href="#">Certificar</a></h3>
                    <div class="text">
                        Muy útil para certificar que algo en una fecha y hora determinada, este ayuda al "no repudio" de algún mensaje electrónico.
                    </div>
                </div>
            </div>

            <!-- Service Block -->
            <div class="service-block-two col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <span class="icon flaticon-contract"></span>
                    <h3><a href="#">Validez</a></h3>
                    <div class="text">
                        Avalada por la Secretaría de Economía le da validez legal. Obteniendo con ello el registro de la fecha, hora exacta, que brinda la hora oficial de México y del mundo. (CENAM y Centro internacional de pesos y medidas)                        </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="contenedor-iconosCircle">
    <section class="cont-icos-circle">
        <div class="cont-icos-SVG">
            <div class="icos-SVG-1">
                <div class="ico-SVG-user">
                    <p>Firmantes</p>
                    <img class="user" src="<?php echo BASE_URL; ?>public/images/icossvg/user.svg">
                    <img class="user" src="<?php echo BASE_URL; ?>public/images/icossvg/user.svg">
                    <p>Receptores de <br> Mensajes</p>
                </div>
                <div class="ico-SVG-user">
                    <img class="firma" src="i<?php echo BASE_URL; ?>public/mages/icossvg/firma.svg">
                    <p>Mensaje firmado</p>
                </div>
            </div>

            <div class="icos-SVG-2">
                <div class="ico-SVG-user">
                    <p>Estampilla <br> de Tiempo</p>
                    <img class="firma" src="<?php echo BASE_URL; ?>public/images/icossvg/sello.svg">
                </div>
                <div class="ico-SVG-user">
                    <img class="sha" src="<?php echo BASE_URL; ?>public/images/icossvg/sha.svg">
                    <p>Digestión</p>
                </div>
            </div>

            <div class="icos-SVG-1">
                <div class="ico-SVG-user">
                    <p>Timestamping <br> Authority (TSA)</p>
                    <img class="firma" src="<?php echo BASE_URL; ?>public/images/icossvg/certificado.svg">
                </div>
                <div class="ico-SVG-user">
                    <img class="pc" src="<?php echo BASE_URL; ?>public/images/icossvg/pc.svg">
                    <p>Digestión</p>
                </div>
            </div>
            <div class="icos-SVG-bottom">
                <div class="ico-SVG-nube">
                    <img class="nube" src="<?php echo BASE_URL; ?>public/images/icossvg/nube.svg">
                    <p>Internet</p>
                </div>
            </div>
        </div>
        <div class="circle"></div>
    </section>
</div>
    
<section class="case-study-section">
    <div class="auto-container">
        <div class="sec-title text-center">
            <h3>¿Entonces qué estas esperando?</h3>
            <div class="text">
                ¡Contáctanos ahora! Te activaremos una cortesia para que <br>
                inicies tu proceso de transformación digital
            </div>

            <div class="box-btns">
                <a class="btn-contacto" href="contact.html">Contacto</a>
                <a class="btn-servicios" href="servicios.html">Servicios</a>
            </div>
        </div>
    </div>
</section>