<section class="process-section" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/2.jpg);">
    <div class="auto-container">
        <div class="row">
            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <span class="icon flaticon-sign"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                    </div>
                    <h4>
                        <a style="color: white;" href="<?php echo BASE_URL; ?>doc2sign/index">Firma digital electrónica.</a>
                    </h4>
                    <div class="text">
                        A través de la firma electrónica avanzada, PSC World pone 
                        a su disposición soluciones para su empresa.
                    </div>
                </div>
            </div>

            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <!-- <span class="icon flaticon-print"></span> -->
                        <span class="icon flaticon-certificate"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                        <!-- <span class="roadmap-divider"></span> -->
                    </div>
                    <h4>
                        <a style="color: white;" href="<?php echo BASE_URL; ?>servicios/estampado_tiempo">Estampado de tiempo.</a>
                    </h4>
                    <div class="text">
                        Te ofrecemos un potente conjunto de caracteristicas:  
                        Fecha y Hora exacta, Certicar y Validez.
                    </div>
                </div>
            </div>

            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <span class="icon flaticon-ssl-certificate"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                        <!-- <span class="roadmap-divider"></span> -->
                    </div>
                    <h4>
                        <a style="color: white;" href="<?php echo BASE_URL; ?>servicios/certificado_ssl">Certificados SSL.</a>
                    </h4>
                    <div class="text">
                        PSC World ofrece 2 tipos de certificados: Rapid SSL y True BusinesslD (para un solo dominio).    
                    </div>
                </div>
            </div>

            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <span class="icon flaticon-paper"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                        <!-- <span class="count title_ff"><span class="flaticon-check"></span></span> -->
                    </div>
                    <h4>
                        <a style="color: white;" href="<?php echo BASE_URL; ?>servicios/nom_151">NOM-151.</a>
                    </h4>
                    <div class="text">
                        La NOM 151 establece los requisitos para la conservación de mensajes de datos y la digitalización de documentos.
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="services-section style-two">
    <div class="auto-container">
        <div class="row">
            <!-- Text column -->
            <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                <div class="inner-column">            
                    <div class="sec-title">
                        <span class="sub-title">Doc2sign</span>
                        <h3>
                            PSC World presenta <br>
                            Doc2sing
                        </h3>
                        <div class="text">
                            <strong>
                                Donde podras firmar a distancia y de forma digital documentos de cualquier tipo desde laborales hasta mercantiles y civiles.
                            </strong>
                        </div>
                    </div>
                    <p>
                        Estarás siempre en cumplimiento de las disposiciones aplicables vigentes, teniendo la seguridad en que el documento firmado será legalmente vinculante.
                    </p>
                    <a href="<?php echo BASE_URL; ?>doc2sign/index" class="theme-btn icon-btn-two">
                        <span>Ir</span>
                    </a>
                </div>
            </div>

            <!-- Image Column -->
            <div class="image-column col-lg-7 col-md-12 col-sm-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/womanComputer.jpg);"></div>
        </div>
    </div>
</section>

<section class="services-section-two" style="padding: 0px;">
    <div class="auto-container">
        
            <div class="sec-title text-center">
                <!-- <span class="icon flaticon-satchel"></span> -->
                <h3>Potente conjunto de caracteristicas</h3>
            </div>


        <div class="row">
            <!-- Service Block -->
            <div class="service-block-two col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <span class="icon flaticon-calendar"></span>
                    <h3><a href="#">Fecha y Hora exacta</a></h3>
                    <div class="text">
                        Permite conocer la fecha y hora exacta de una operación electrónica dentro de un sistema informático, permitiendo la restreabilidad y la validación de integridad del documento o archivo electrónico
                    </div>
                </div>
            </div>

            <!-- Service Block -->
            <div class="service-block-two col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <span class="icon flaticon-patent"></span>
                    <h3><a href="#">Certificar</a></h3>
                    <div class="text">
                        Muy útil para certificar que algo en una fecha y hora determinada, este ayuda al "no repudio" de algún mensaje electrónico.
                    </div>
                </div>
            </div>

            <!-- Service Block -->
            <div class="service-block-two col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <span class="icon flaticon-contract"></span>
                    <h3><a href="#">Validez</a></h3>
                    <div class="text">
                        Avalada por la Secretaría de Economía le da validez legal. Obteniendo con ello el registro de la fecha, hora exacta, que brinda la hora oficial de México y del mundo. (CENAM y Centro internacional de pesos y medidas)                        </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="fluid-section-four">
    <div class="auto-container">
        <div class="row">
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <h3>
                            NOM-151
                        </h3>
                        <div class="text">
                            La NOM 151 establece los requisitos para la conservación de mensajes de datos y la digitalización de documentos.
                        </div>

                        <strong>
                            <br>
                            Esta norma está pensada para cuando se pretenda almacenar en un medio electrónico, óptico o de cualquier otra tecnologia, información derivada de un acto de comercio que se encuentre soportada en un medio fisico, los comerciantes podrán optar por migrar dicha información a una forma digital.
                        </strong>
                    </div>
                    <a href="<?php echo BASE_URL; ?>servicios/nom_151" class="theme-btn icon-btn-two">
                        <span>Ir</span>
                    </a>
                </div>
            </div>

            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12">
                <div class="image-layer" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/18.jpg);"></div>
            </div>
        </div>
    </div>
</section>

<section class="contact-form-section">
    <div class="auto-container">
        <div class="row form-outer">
            <!-- Image Column -->
            <div class="image-column col-lg-6 col-md-12 col-sm-12">
                <div class="layer-image" style="background-image: url(<?php echo BASE_URL; ?>/public/images/vertorSSL.jpg);"></div>
            </div>

            
            <div class="form-column col-lg-6 col-md-12 col-sm-12">
                <div class="default-form contact-form">
                    <div class="title">
                        <h4>Certificados SSL</h4>
                        <p>
                            Es un titulo digital que 
                            <b>autentica la identidad de un sitio web  </b>
                            y cifra con tecnologia SSL (Secure Sockets Layer) la información que se envía al servidor.
                            <br><br>
                            Este protocolo logra que la transmisión 
                            de datos entre un servidor y un usuario a 
                            través de internet, sea completamente 
                            segura y <b> asegurando la protección de datos 
                            personales </b> o sigilosos que circulan en la web.
                            <br><br>
                            PSC World ofrece 2 tipos de certificados: 
                            <b>Rapid SSL y True BusinesslD </b> (para un solo dominio).
                        </p>
                    </div>
                    <a href="<?php echo BASE_URL; ?>servicios/certificado_ssl" class="theme-btn icon-btn-two">
                        <span>Ir</span>
                    </a>
                </div>  
            </div>
        </div>
    </div>
</section> 