<section class="fluid-section-four">
    <div class="auto-container">
        <div class="row">
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <h3>
                            NOM-151
                        </h3>
                        <div class="text">
                            La NOM 151 establece los requisitos para la conservación de mensajes de datos y la digitalización de documentos.
                        </div>

                        <strong>
                            <br>
                            Esta norma está pensada para cuando se pretenda almacenar en un medio electrónico, óptico o de cualquier otra tecnologia, información derivada de un acto de comercio que se encuentre soportada en un medio fisico, los comerciantes podrán optar por migrar dicha información a una forma digital.
                        </strong>
                    </div>
                </div>
            </div>

            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12">
                <!-- <div class="image-layer" style="background-image: url(images/background/18.jpg);"></div> -->
                <div class="image-layer" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/18.jpg);"></div>
            </div>
        </div>
    </div>
</section>

<section class="fluid-section-two">
    <div class="container-fluid">
        <div class="row no-gutters">
            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/mancomputer.jpg);"></div>
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <!-- <span class="sub-title">innovations</span> -->
                        <h3>
                            La solución perfecta <br> para comerciantes.
                        </h3>
                        <div class="text">
                            <strong>Comerciantes que tienen la obligación de</strong>

                            <ul class="list-style-one">
                                <li>
                                    Llevar y mantener un sistema de contabilidad adecuado.
                                </li>
                                <li>
                                    Conservar documentación relacionada con su negocio.
                                </li>
                                <li>
                                    Preservar documentos que consignen 
                                    <b> contratos, convenios o compromisos que originen derechos y obligaciones.</b>
                                </li>
                                <li>
                                    Todo lo relativo al capitulo de mensajes de datos del código de Comercio.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>