<section class="contact-form-section">
    <div class="auto-container">
        <div class="row form-outer">
            <!-- Image Column -->
            <div class="image-column col-lg-6 col-md-12 col-sm-12">
                <div class="layer-image" style="background-image: url(<?php echo BASE_URL; ?>/public/images/imgcontacto.jpg);"></div>
            </div>

            <!-- Form Column -->
            <div class="form-column col-lg-6 col-md-12 col-sm-12">
                <div class="default-form contact-form">
                    <div class="title">
                        <h4>Envia un mensaje</h4>
                        <p>
                            Por favor llene el formulario con la información 
                            que es solicitada a continuación.
                        </p>
                    </div>

                    <form action="#" method="post" id="email-form">
                        <div class="row mid-spacing" action="<?php echo BASE_URL ?>contacto/enviar/" method="post">
                            <div class="form-group mb-0 col-lg-12">
                                <div class="response"></div>
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <input type="text" name="nombre" class="first_name" placeholder="Nombre" required="">
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <input type="text" name="apellido" class="last_name" placeholder="Apellido" required="">
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <input type="text" name="telefono" class="first_name" placeholder="Teléfono" required="">
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <input type="text" name="estado" class="last_name" placeholder="Estado" required="">
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <input type="text" name="nombreEmpresa" class="first_name" placeholder="Nombre de la empresa" required="">
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <input type="text" name="tamanoEmpresa" class="last_name" placeholder="Tamaño de la empresa" required="">
                            </div>

                            <div class="form-group col-lg-12 col-md-6 col-sm-12">
                                <input type="email" name="email" class="email" placeholder="Correo" required="">
                            </div>
                            
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                <textarea name="mensaje" placeholder="Mensaje"></textarea>
                            </div>
                            
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                <button class="theme-btn btn-style-four" type="button" id="submit" name="submit-form">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>  
            </div>
        </div>
    </div>
</section>
<section class="contact-map-section">
    <div class="map-outer">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3763.200204105295!2d-99.1799300842911!3d19.40375390949392!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1ff6629938d97%3A0x826ce801c68ba47e!2sAvenida%20Patriotismo%2048%2C%20Escand%C3%B3n%20I%20Secc%2C%20Miguel%20Hidalgo%2C%2011800%20Ciudad%20de%20M%C3%A9xico%2C%20CDMX%2C%20M%C3%A9xico!5e0!3m2!1ses!2sco!4v1598563919900!5m2!1ses!2sco" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
</section>