 <!--Main Slider-->
    <section class="main-slider">
        <div class="rev_slider_wrapper fullwidthbanner-container"  id="rev_slider_one_wrapper" data-source="gallery">
            <div class="rev_slider fullwidthabanner" id="rev_slider_one" data-version="5.4.1">
                <ul>

                    <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="300"  data-thumb=""  data-delay="5000"  data-rotate="0"  data-saveperformance="off"  data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                        
                        <img src="<?php echo BASE_URL; ?>public/images/main-slider/1.jpg" title="head" data-bg="p:center top;" data-parallax="off" class="rev-slidebg" data-no-retina>
                        <!-- LAYERS -->

                        <div class="tp-caption" 
                        data-paddingbottom="[0,0,0,0]"
                        data-paddingleft="[15,15,15,15]"
                        data-paddingright="[15,15,15,15]"
                        data-paddingtop="[0,0,0,0]"
                        data-responsive_offset="on"
                        data-type="text"
                        data-height="none"
                        data-width="['750','750','750','650']"
                        data-whitespace="normal"
                        data-hoffset="['0','0','0','0']"
                        data-voffset="['-80','-80','-100','-100']"
                        data-x="['left','left','center','center']"
                        data-y="['middle','middle','middle','middle']"
                        data-textalign="['top','top','top','top']"
                        data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                        <h2>
                            Firma contratos en linea
                            utilizando Doc2Sign
                        </h2>
                        </div>

                        <div class="tp-caption" 
                        data-paddingbottom="[0,0,0,0]"
                        data-paddingleft="[15,15,15,15]"
                        data-paddingright="[15,15,15,15]"
                        data-paddingtop="[0,0,0,0]"
                        data-responsive_offset="on"
                        data-type="text"
                        data-height="none"
                        data-whitespace="normal"
                        data-width="['650','650','650','250']"
                        data-hoffset="['0','0','0','0']"
                        data-voffset="['100','100','120','120']"
                        data-x="['left','left','center','center']"
                        data-y="['middle','middle','middle','middle']"
                        data-textalign="['top','top','top','top']"
                        data-frames='[{"delay":500,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <div class="btn-box">
                                <a href="#" class="theme-btn btn-style-one"><span class="btn-title">Conoce más</span></a>
                            </div>
                        </div>
                    </li>

                    <li data-index="rs-2" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="300"  data-thumb=""  data-delay="5000"  data-rotate="0"  data-saveperformance="off"  data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                        
                        <img src="<?php echo BASE_URL; ?>public/images/main-slider/1.jpg" title="head" data-bg="p:center top;" data-parallax="off" class="rev-slidebg" data-no-retina>
                        <!-- LAYERS -->

                        <div class="tp-caption" 
                        data-paddingbottom="[0,0,0,0]"
                        data-paddingleft="[15,15,15,15]"
                        data-paddingright="[15,15,15,15]"
                        data-paddingtop="[0,0,0,0]"
                        data-responsive_offset="on"
                        data-type="text"
                        data-height="none"
                        data-width="['750','750','750','650']"
                        data-whitespace="normal"
                        data-hoffset="['0','0','0','0']"
                        data-voffset="['-80','-80','-100','-100']"
                        data-x="['left','left','center','center']"
                        data-y="['middle','middle','middle','middle']"
                        data-textalign="['top','top','top','top']"
                        data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            
                            <h2>Aseguramos sus negocios digitales </h2>
                        </div>

                        <div class="tp-caption" 
                        data-paddingbottom="[0,0,0,0]"
                        data-paddingleft="[15,15,15,15]"
                        data-paddingright="[15,15,15,15]"
                        data-paddingtop="[0,0,0,0]"
                        data-responsive_offset="on"
                        data-type="text"
                        data-height="none"
                        data-whitespace="normal"
                        data-width="['650','650','650','250']"
                        data-hoffset="['0','0','0','0']"
                        data-voffset="['100','100','120','120']"
                        data-x="['left','left','center','center']"
                        data-y="['middle','middle','middle','middle']"
                        data-textalign="['top','top','top','top']"
                        data-frames='[{"delay":500,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <div class="btn-box">
                                <a href="#" class="theme-btn btn-style-one"><span class="btn-title">Conoce más</span></a>
                            </div>
                        </div>
                    </li>

                    <li data-index="rs-3" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="300"  data-thumb=""  data-delay="5000"  data-rotate="0"  data-saveperformance="off"  data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                        
                        <img src="<?php echo BASE_URL; ?>public/images/main-slider/1.jpg" title="head" data-bg="p:center top;" data-parallax="off" class="rev-slidebg" data-no-retina>
                        <!-- LAYERS -->

                        <div class="tp-caption" 
                        data-paddingbottom="[0,0,0,0]"
                        data-paddingleft="[15,15,15,15]"
                        data-paddingright="[15,15,15,15]"
                        data-paddingtop="[0,0,0,0]"
                        data-responsive_offset="on"
                        data-type="text"
                        data-height="none"
                        data-width="['750','750','750','650']"
                        data-whitespace="normal"
                        data-hoffset="['0','0','0','0']"
                        data-voffset="['-80','-80','-100','-100']"
                        data-x="['left','left','center','center']"
                        data-y="['middle','middle','middle','middle']"
                        data-textalign="['top','top','top','top']"
                        data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <h2>processing</h2>
                        </div>

                        <div class="tp-caption" 
                        data-paddingbottom="[0,0,0,0]"
                        data-paddingleft="[15,15,15,15]"
                        data-paddingright="[15,15,15,15]"
                        data-paddingtop="[0,0,0,0]"
                        data-responsive_offset="on"
                        data-type="text"
                        data-height="none"
                        data-width="['520','520','600','455']"
                        data-whitespace="normal"
                        data-hoffset="['0','0','0','0']"
                        data-voffset="['0','0','0','0']"
                        data-x="['left','left','center','center']"
                        data-y="['middle','middle','middle','middle']"
                        data-textalign="['top','top','top','top']"
                        data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <div class="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna  </div>
                        </div>
                        
                        <div class="tp-caption" 
                        data-paddingbottom="[0,0,0,0]"
                        data-paddingleft="[15,15,15,15]"
                        data-paddingright="[15,15,15,15]"
                        data-paddingtop="[0,0,0,0]"
                        data-responsive_offset="on"
                        data-type="text"
                        data-height="none"
                        data-whitespace="normal"
                        data-width="['650','650','650','250']"
                        data-hoffset="['0','0','0','0']"
                        data-voffset="['100','100','120','120']"
                        data-x="['left','left','center','center']"
                        data-y="['middle','middle','middle','middle']"
                        data-textalign="['top','top','top','top']"
                        data-frames='[{"delay":500,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <div class="btn-box">
                                <a href="#" class="theme-btn btn-style-one"><span class="btn-title">Read More</span></a>
                            </div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </section>
    <!--End Main Slider-->

    <!-- Case Study Section -->
    <section class="case-study-section">
        <div class="auto-container">
            <div class="sec-title text-center">
                <span class="icon flaticon-inspiration"></span>
                <h3>¿Cómo lo hacemos?</h3>
                <div class="text">
                    PSC World es una empresa que se preocupa por tu seguridad digital, ofreciendo servicios<br>
                    que resuelven las necesidades y problemas de nuestros clientes
                </div>
            </div>

            <div class="row">
                <!-- Case Block -->
                <div class="case-block col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image"><a href="service-detail.html"><img src="<?php echo BASE_URL; ?>public/images/resource/case-1.jpg" alt=""></a></figure>
                            <span class="icon_img"><img src="<?php echo BASE_URL; ?>public/images/icons/case_icon_1.png" alt=""></span>
                        </div>
                        <div class="lower-content">
                            <h4><a href="service-detail.html">Certificamos sus comunicaciones</a></h4>
                            <div class="text">
                                Estamos certificados por la Secretaria de Comercio y podemos ofrecer seguridad y encriptación en todas sus comunicaciones para que tengan valor legal.
                            </div>
                            <div class="btn-box">
                                <a href="service-detail.html" class="theme-btn icon-btn-one"><span>Empezar</span></a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Case Block -->
                <div class="case-block col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image"><a href="service-detail.html"><img src="<?php echo BASE_URL; ?>public/images/resource/case-2.jpg" alt=""></a></figure>
                            <span class="icon_img"><img src="<?php echo BASE_URL; ?>public/images/icons/case_icon_2.png" alt=""></span>
                        </div>
                        <div class="lower-content">
                            <h4><a href="service-detail.html">Apoyo de Oficiales Jurídicos</a></h4>
                            <div class="text">
                                Nuestro equipo cuenta con la experiencia jurídica para apoyarlo en la implementación de sus certificados digitales.
                            </div>
                            <div class="btn-box">
                                <a href="service-detail.html" class="theme-btn icon-btn-one"><span>Fundamento legal</span></a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Case Block -->
                <div class="case-block col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image"><a href="service-detail.html"><img src="<?php echo BASE_URL; ?>public/images/resource/case-3.jpg" alt=""></a></figure>
                            <span class="icon_img"><img src="<?php echo BASE_URL; ?>public/images/icons/case_icon_3.png" alt=""></span>
                        </div>
                        <div class="lower-content">
                            <h4><a href="service-detail.html">Alianzas y herramientas</a></h4>
                            <div class="text">
                                Ponemos a su disposición la experiencia de nuestros aliados en seguridad para proveer los mejores servicios de seguridad.
                            </div>
                            <div class="btn-box">
                                <a href="service-detail.html" class="theme-btn icon-btn-one"><span>Conoce más</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="sec-bottom-text">Los servicios de PSC World lo ayudaran a tener éxito. <a href="#">Empecemos</a></div>
        </div>
    </section>
    <!-- End Case Study Section -->

    <!-- Clients Section -->
    <section class="clients-section">
        <div class="auto-container">

            <!-- Sponsors Outer -->
            <div class="sponsors-outer">
                <!--Sponsors Carousel-->
                <ul class="sponsors-carousel owl-carousel owl-theme">
                    <li class="slide-item">
                        <a href="https://www.soriana.com/">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/1_hover.png" alt="" class="hover_img">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/1.png" alt="">
                        </a>
                    </li>
                    <li class="slide-item">
                        <a href="https://aserta.com.es/">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/2_hover.png" alt="" class="hover_img">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/2.png" alt="">
                        </a>
                    </li>
                    <li class="slide-item">
                        <a href="https://tec.mx/es">
                            <img  class="hover_img" id="logoEmpresa3" src="<?php echo BASE_URL; ?>public/images/clients/3_hover.png" alt="">
                            <img id="logoEmpresa3" src="<?php echo BASE_URL; ?>public/images/clients/3.png" alt="">
                        </a>
                    </li>
                    <li class="slide-item">
                        <a href="https://www.inbursa.com/">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/4_hover.png" alt="" class="hover_img">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/4.png" alt="">
                        </a>
                    </li>
                    <li class="slide-item">
                        <a href="https://www.fianzasatlas.com.mx/">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/5_hover.png" alt="" class="hover_img">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/5.png" alt="">
                        </a>
                    </li>
                    <li class="slide-item">
                        <a href="http://www.metrofinanciera.com/">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/6_hover.png" alt="" class="hover_img">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/6.png" alt="">
                        </a>
                    </li>
                    <li class="slide-item">
                        <a href="https://www.chubb.com/mx-es/">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/7_hover.png" alt="" class="hover_img">
                            <img src="<?php echo BASE_URL; ?>public/images/clients/7.png" alt="">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <!--End Clients Section -->

    <!-- Process Section -->
    <section class="process-section" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/2.jpg);">
        <div class="auto-container">
            <div class="row">
                <!-- Process BLock -->
                <div class="process-block col-lg-3 col-md-6 col-sm-12">
                    <div class="inner-box active">
                        <div class="icon-box">
                            <!-- <span class="icon flaticon-pen"></span> -->
                            <span class="icon flaticon-sign"></span>
                            <span class="count title_ff"><span class="flaticon-check"></span></span>
                            <!-- <span class="roadmap-divider"></span> -->
                        </div>
                        <h4>Firma digital electrónica.</h4>
                        <div class="text">
                            A través de la firma electrónica avanzada, PSC World pone 
                            a su disposición soluciones para su empresa.
                        </div>
                    </div>
                </div>

                <!-- Process BLock -->
                <div class="process-block col-lg-3 col-md-6 col-sm-12">
                    <div class="inner-box active">
                        <div class="icon-box">
                            <!-- <span class="icon flaticon-print"></span> -->
                            <span class="icon flaticon-certificate"></span>
                            <span class="count title_ff"><span class="flaticon-check"></span></span>
                            <!-- <span class="roadmap-divider"></span> -->
                        </div>
                        <h4>Estampado de tiempo</h4>
                        <div class="text">
                            Te ofrecemos un potente conjunto de caracteristicas:  
                            Fecha y Hora exacta, Certicar y Validez.
                        </div>
                    </div>
                </div>

                <!-- Process BLock -->
                <div class="process-block col-lg-3 col-md-6 col-sm-12">
                    <div class="inner-box active">
                        <div class="icon-box">
                            <span class="icon flaticon-ssl-certificate"></span>
                            <span class="count title_ff"><span class="flaticon-check"></span></span>
                            <!-- <span class="roadmap-divider"></span> -->
                        </div>
                        <h4>Certificados SSL</h4>
                        <div class="text">
                            PSC World ofrece 2 tipos de certificados: Rapid SSL y True BusinesslD (para un solo dominio).    
                        </div>
                    </div>
                </div>

                <!-- Process BLock -->
                <div class="process-block col-lg-3 col-md-6 col-sm-12">
                    <div class="inner-box active">
                        <div class="icon-box">
                            <span class="icon flaticon-paper"></span>
                            <span class="count title_ff"><span class="flaticon-check"></span></span>
                            <!-- <span class="count title_ff"><span class="flaticon-check"></span></span> -->
                        </div>
                        <h4>NOM-151</h4>
                        <div class="text">
                            La NOM 151 establece los requisitos para la conservación de mensajes de datos y la digitalización de documentos.
                        </div>
                    </div>
                </div>
            </div>

            <!-- <div class="btn-box">
                <div class="text">We believe that designing products and services in close partnership with our clients is the only <br>way to have a real impact on their business.</div>
                <a href="#" class="theme-btn btn-style-two"><i class="flaticon-time-left"></i>About Our Process</a>
            </div> -->
        </div>
    </section>
    <!--End Process Section -->

    <!-- Consultation Section -->
    <section class="consultation-section">
        <div class="upper-banner" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/3.jpg);">
            <div class="auto-container">
                <div class="sec-title-two light">
                    <span class="icon flaticon-inspiration"></span>
                    <h3>Consulta Gratis</h3>
                    <div class="text">
                        Te damos la bienvenida al soporte tecnico 
                        de PSC Wolrd. <br> ¿Como podemos ayudarte?
                    </div>
                </div>
            </div>
        </div>

        <!-- Form Container -->
        <div class="form-container">
            <div class="auto-container">
                <form class="form-style-one">
                    <div class="row">
                        <div class="form-group col-lg-4 col-md-6 col-sm-12">
                            <label>Nombre <sup>*</sup></label>
                            <div class="input-group">
                                <span class="icon fa fa-user"></span>
                                <input type="text" name="firstname" placeholder="Juan" required="">
                            </div>
                        </div>

                        <div class="form-group col-lg-4 col-md-6 col-sm-12">
                            <label>Apellido <sup>*</sup></label>
                            <div class="input-group">
                                <span class="icon fa fa-user"></span>
                                <input type="text" name="lastname" placeholder="Hernández" required="">
                            </div>
                        </div>

                        <div class="form-group col-lg-4 col-md-6 col-sm-12">
                            <label>¿De qué trata tu consulta?  <sup>*</sup></label>
                            <div class="input-group">
                                <span class="icon fa fa-info"></span>
                                <select name="inquiry" required="required">
                                    <option value="" class="placeholder" disabled="" selected="selected">Por favor seleccione</option>
                                    <option value="First Choice">First Choice</option>
                                    <option value="Second Choice">Second Choice</option>
                                    <option value="Third Choice">Third Choice</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group col-lg-4 col-md-6 col-sm-12">
                            <label>Número de teléfono <sup>*</sup></label>
                            <div class="input-group">
                                <span class="icon fa fa-phone-volume"></span>
                                <input type="text" name="phone" placeholder="Numero completo" required="">
                            </div>
                        </div>
                        
                        <div class="form-group col-lg-4 col-md-6 col-sm-12">
                            <label>Correo electrónico <sup>*</sup></label>
                            <div class="input-group">
                                <span class="icon fa fa-envelope"></span>
                                <input type="email" name="email" placeholder="nombre@empresa.com" required="">
                            </div>
                        </div>

                        <div class="form-group col-lg-4 col-md-6 col-sm-12">
                            <label></label>
                            <button class="theme-btn btn-style-one" type="submit" name="submit-form">Obtenga una consulta gratuita</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- End Consultation Section -->

    <!-- Testimonials Section -->
    <section class="testimonials-section">
        <div class="container-fluid">
            <div class="sec-title text-center">
                <span class="icon flaticon-user"></span>
                <h3>¿Qué opinan nuestros clientes?</h3>
                <div class="text">
                    Hoy en día, las empresas cruzan fronteras y regiones, por lo que necesita un <br> proveedor de servicios que vaya donde usted se encuentre.    
                </div>
            </div>

            <div class="row">
                
                <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                        <div class="content">
                            <p>
                                Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                            </p>
                            <span class="author">Carlos R.</span>
                        </div>
                    </div>
                </div>

                
                <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                        <div class="content">
                            <p>
                                Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                            </p>
                            <span class="author">Yan A.</span>
                        </div>
                    </div>
                </div>

                
                <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                        <div class="content">
                            <p>
                                Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                            </p>
                            <span class="author">Carlos R.</span>
                        </div>
                    </div>
                </div>

                
                <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <div class="inner-box">
                        <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                        <div class="content">
                            <p>
                                Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                            </p>
                            <span class="author">Yan A.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Case Study Section -->

    <section class="clients-section">
        <div class="auto-container">
            <div class="sponsors-outer">
                <p style="text-align: center; padding-bottom: 40px; font-size: 18px;">
                    Ellos son nuestros Aliados ¿Te
                    interesaria formar parte? Contáctanos 
                    o revisa nuestros
                    <a href=""><b>planes de convenio.</b></a>
                </p>
                <div class="container-aliados">
                    <a href="http://www.detecno.com/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/detecno_hover.png">
                    </a>
                    <a href="http://www.karalundi.com.mx/esp/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/karalundi_hover.png">
                    </a>
                    <a href="https://www.datavision.com.mx/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/datavision_hover.png">
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section class="news-section">
        <div class="auto-container">
            <div class="sec-title text-center">
                <span class="icon flaticon-news"></span>
                <h3>Últimas Noticias</h3>
                <div class="text">
                    Hoy en día, las empresas cruzan fronteras y regiones, por lo que necesita un <br>
                    proveedor de servicios que vaya donde usted se encuentre.    
                </div>
            </div>

            <div class="row">
                
                <div class="news-block col-lg-4 col-md-6 col-sm-12 wow fadeInUp">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image"><a href="blog-post-image.html"><img src="<?php echo BASE_URL; ?>public/images/resource/news-1.jpg" alt=""></a></figure>
                            <a href="#" class="date"><i class="far fa-calendar"></i> Sep 8, 2020</a>
                        </div>
                        <div class="lower-content">
                            <a href="#" class="read-more"><i class="flaticon-right-arrow"></i></a>
                            <h4><a href="blog-post-image.html">
                                Emisión y entraga del CFDI de nóminas: Las dos caras de la moneda.
                            </a></h4>
                            <div class="text">
                                Es importante mencionar que para efectos de la deducción de la nómina, los patrones deberán emitir un CFDI por cada uno de los 
                            </div>
                            <div class="post-info">
                                <div class="post-author">
                                    <img src="<?php echo BASE_URL; ?>public/images/resource/author-thumb.png" alt="" />
                                    admin
                                </div>

                                <div class="post-option">
                                    <div class="coments_count"><a href="#"><i class="fa fa-comment"></i>0</a></div>
                                    <ul class="social-share">
                                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                
                <div class="news-block col-lg-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="400ms">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image"><a href="blog-post-image.html"><img src="<?php echo BASE_URL; ?>public/images/resource/news-2.jpg" alt=""></a></figure>
                            <a href="#" class="date"><i class="far fa-calendar"></i> Sep 8, 2020</a>
                        </div>
                        <div class="lower-content">
                            <a href="#" class="read-more"><i class="flaticon-right-arrow"></i></a>
                            <h4><a href="blog-post-image.html">
                                Emisión y entraga del CFDI de nóminas: Las dos caras de la moneda.
                            </a></h4>
                            <div class="text">
                                Es importante mencionar que para efectos de la deducción de la nómina, los patrones deberán emitir un CFDI por cada uno de los 
                            </div>
                            <div class="post-info">
                                <div class="post-author">
                                    <img src="<?php echo BASE_URL; ?>public/images/resource/author-thumb.png" alt="" />
                                    admin
                                </div>

                                <div class="post-option">
                                    <div class="coments_count"><a href="#"><i class="fa fa-comment"></i>0</a></div>
                                    <ul class="social-share">
                                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                
                <div class="news-block col-lg-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="800ms">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image"><a href="blog-post-image.html"><img src="<?php echo BASE_URL; ?>public/images/resource/news-3.jpg" alt=""></a></figure>
                            <a href="#" class="date"><i class="far fa-calendar"></i> Sep 8, 2020</a>
                        </div>
                        <div class="lower-content">
                            <a href="#" class="read-more"><i class="flaticon-right-arrow"></i></a>
                            <h4><a href="blog-post-image.html">
                                Emisión y entraga del CFDI de nóminas: Las dos caras de la moneda.
                            </a></h4>
                            <div class="text">
                                Es importante mencionar que para efectos de la deducción de la nómina, los patrones deberán emitir un CFDI por cada uno de los 
                            </div>
                            <div class="post-info">
                                <div class="post-author">
                                    <img src="<?php echo BASE_URL; ?>public/images/resource/author-thumb.png" alt="" />
                                    admin
                                </div>

                                <div class="post-option">
                                    <div class="coments_count"><a href="#"><i class="fa fa-comment"></i>0</a></div>
                                    <ul class="social-share">
                                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="sec-bottom-text">
                Información que le ayudará a hacer lo que hace mejor, más rápido y de forma más rentable. <a href="noticias.html">Leer el blog completo</a>
            </div>
        </div>
    </section>
    
    <section class="call-to-action" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/4.jpg);">
        <div class="auto-container">
            <div class="content">
                <div class="sec-title-two">
                    <span class="icon flaticon-question-1"></span>
                    <h3>Estamos aquí para ayudar</h3>
                    <div class="text">Potencia tu empresa con PSC World.</div>
                </div>
                
                <div class="btn-box">
                    <a href="service-detail.html" class="theme-btn icon-btn-two"><span>Obtén ayuda aquí</span></a>
                </div>
            </div>
        </div>
    </section>