 <!--Main Slider-->
<section class="main-slider">
    <div class="rev_slider_wrapper fullwidthbanner-container"  id="rev_slider_one_wrapper" data-source="gallery">
        <div class="rev_slider fullwidthabanner" id="rev_slider_one" data-version="5.4.1">
            <ul>
                <?php foreach ($this->banners as $key => $value) { ?>
                <li data-index="rs-<?php echo $key+1 ?>" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="300"  data-thumb=""  data-delay="5000"  data-rotate="0"  data-saveperformance="off"  data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <!-- MAIN IMAGE -->
                    
                    <img src="<?php echo BASE_URL; ?>public/images/banners/<?php echo $value->getId(); ?>.jpg" title="head" data-bg="p:center top;" data-parallax="off" class="rev-slidebg" data-no-retina>
                    <!-- LAYERS -->

                    <div class="tp-caption" 
                    data-paddingbottom="[0,0,0,0]"
                    data-paddingleft="[15,15,15,15]"
                    data-paddingright="[15,15,15,15]"
                    data-paddingtop="[0,0,0,0]"
                    data-responsive_offset="on"
                    data-type="text"
                    data-height="none"
                    data-width="['750','750','750','650']"
                    data-whitespace="normal"
                    data-hoffset="['0','0','0','0']"
                    data-voffset="['-80','-80','-100','-100']"
                    data-x="['left','left','center','center']"
                    data-y="['middle','middle','middle','middle']"
                    data-textalign="['top','top','top','top']"
                    data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                    <h2>
                        <?php echo $value->getTitulo(); ?>
                    </h2>
                    </div>

                    <div class="tp-caption" 
                    data-paddingbottom="[0,0,0,0]"
                    data-paddingleft="[15,15,15,15]"
                    data-paddingright="[15,15,15,15]"
                    data-paddingtop="[0,0,0,0]"
                    data-responsive_offset="on"
                    data-type="text"
                    data-height="none"
                    data-whitespace="normal"
                    data-width="['650','650','650','250']"
                    data-hoffset="['0','0','0','0']"
                    data-voffset="['100','100','120','120']"
                    data-x="['left','left','center','center']"
                    data-y="['middle','middle','middle','middle']"
                    data-textalign="['top','top','top','top']"
                    data-frames='[{"delay":500,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                    <?php if($value->getUrl()){ ?>
                        <div class="btn-box">
                            <a href="https://<?php echo $value->getUrl() ?>" target="_blank" class="theme-btn btn-style-one"><span class="btn-title">Conoce más</span></a>
                        </div>
                    <?php } ?>
                    </div>
                </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</section>
<!--End Main Slider-->
<?php if(Session::get('autenticado')){ ?>
<div class="container-btn-banner">
    <div class="btn-banner">
        <a href="<?php echo BASE_URL; ?>banner">Editar Banner</a>
    </div>
</div>
<?php } ?>

<!-- Case Study Section -->
<section class="case-study-section">
    <div class="auto-container">
        <div class="sec-title text-center">
            <span class="icon flaticon-inspiration"></span>
            <h3>¿Cómo lo hacemos?</h3>
            <div class="text">
            En PSC World estamos acreditados por la Secretaría de Economía como prestador <br>
            de servicios de certificación desde el año 2005. 
            <br><br> Queremos ser tu aliado en la transformación digital de tu empresa, conoce nuestros <br>
            servicios de generación de certificados y firma digital con validez legal.
            </div>
        </div>

        <div class="row">
            <!-- Case Block -->
            <div class="case-block col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <div class="image-box">
                        <figure class="image"><a href="service-detail.html"><img src="<?php echo BASE_URL; ?>public/images/resource/case-1.jpg" alt=""></a></figure>
                        <span class="icon_img"><img src="<?php echo BASE_URL; ?>public/images/icons/case_icon_1.png" alt=""></span>
                    </div>
                    <div class="lower-content">
                        <h4><a href="service-detail.html">Optimizamos sus procesos</a></h4>
                        <div class="text">
                        Transforma tu proceso y empieza a firmar contratos con clientes, 
                        proveedores y documentos laborales, con todas las evidencias 
                        normativas necesarias.  
                        </div>
                        <div class="btn-box">
                            <a href="<?php echo BASE_URL; ?>doc2sign" class="theme-btn icon-btn-one">
                                <span>Empezar</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Case Block -->
            <div class="case-block col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <div class="image-box">
                        <figure class="image"><a href="service-detail.html"><img src="<?php echo BASE_URL; ?>public/images/resource/case-2.jpg" alt=""></a></figure>
                        <span class="icon_img"><img src="<?php echo BASE_URL; ?>public/images/icons/case_icon_2.png" alt=""></span>
                    </div>
                    <div class="lower-content">
                        <h4><a href="service-detail.html">Experiencia</a></h4>
                        <div class="text">
                        Desde el año 2005, estamos acreditados por la Secretaría de Economía 
                        y respaldados por nuestro equipo de trabajo con amplia experiencia 
                        jurídica y tecnológica
                        </div>
                        <div class="btn-box">
                            <a href="<?php echo BASE_URL; ?>contacto" class="theme-btn icon-btn-one"><span>Contáctanos</span></a>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Case Block -->
            <div class="case-block col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <div class="image-box">
                        <figure class="image"><a href="service-detail.html"><img src="<?php echo BASE_URL; ?>public/images/resource/case-3.jpg" alt=""></a></figure>
                        <span class="icon_img"><img src="<?php echo BASE_URL; ?>public/images/icons/case_icon_3.png" alt=""></span>
                    </div>
                    <div class="lower-content">
                        <h4><a href="service-detail.html">Funcionalidad</a></h4>
                        <div class="text">
                        Con nuestros servicios de firmado podrás firmar con tu e-firma 
                        (FIEL) del SAT, con una firma digital autógrafa, con un NIP 
                        o con un biométrico, con plena certeza jurídica.  
                        </div>
                        <div class="btn-box">
                            <a href="<?php echo BASE_URL; ?>contacto" class="theme-btn icon-btn-one"><span>Contáctanos</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="sec-bottom-text">
            Los servicios de PSC World lo ayudaran a tener éxito contando 
            además con plena certeza jurídica e integridad en los mensajes 
            de datos que genere. 
            <a href="<?php echo BASE_URL; ?>contacto">Empecemos</a>
        </div>
    </div>
</section>
<!-- End Case Study Section -->

<!-- Clients Section -->
<!-- <section class="clients-section">
    <div class="auto-container">
        <div class="sponsors-outer">
            <ul class="sponsors-carousel owl-carousel owl-theme">
                <li class="slide-item">
                    <a target="_blank" href="https://www.soriana.com/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/1_hover.png" alt="" class="hover_img">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/1.png" alt="">
                    </a>
                </li>
                <li class="slide-item">
                    <a target="_blank" href="https://aserta.com.es/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/2_hover.png" alt="" class="hover_img">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/2.png" alt="">
                    </a>
                </li>
                <li class="slide-item">
                    <a target="_blank" href="https://tec.mx/es">
                        <img  class="hover_img" id="logoEmpresa3" src="<?php echo BASE_URL; ?>public/images/clients/3_hover.png" alt="">
                        <img id="logoEmpresa3" src="<?php echo BASE_URL; ?>public/images/clients/3.png" alt="">
                    </a>
                </li>
                <li class="slide-item">
                    <a target="_blank" href="https://www.inbursa.com/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/4_hover.png" alt="" class="hover_img">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/4.png" alt="">
                    </a>
                </li>
                <li class="slide-item">
                    <a target="_blank" href="https://www.fianzasatlas.com.mx/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/5_hover.png" alt="" class="hover_img">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/5.png" alt="">
                    </a>
                </li>
                <li class="slide-item">
                    <a target="_blank" href="http://www.metrofinanciera.com/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/6_hover.png" alt="" class="hover_img">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/6.png" alt="">
                    </a>
                </li>
                <li class="slide-item">
                    <a target="_blank" href="https://www.chubb.com/mx-es/">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/7_hover.png" alt="" class="hover_img">
                        <img src="<?php echo BASE_URL; ?>public/images/clients/7.png" alt="">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section> -->
<!--End Clients Section -->

<!-- Process Section -->
<section class="process-section" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/2.jpg);">
    <div class="auto-container">
        <p class="txt-a-center">Prestador de Servicios de Certificación</p>
        <div class="row">
            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <!-- <span class="icon flaticon-pen"></span> -->
                        <span class="icon flaticon-sign"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                        <!-- <span class="roadmap-divider"></span> -->
                    </div>
                    <h4>Emisión de Certificados de Firma Electrónica Avanzada.</h4>
                    <div class="text">
                    A través de estos puedes firmar electrónicamente con 
                    el uso de certificados emitidos por una Autoridad 
                    Certificadora con NO Repudio. 
                    </div>
                </div>
            </div>

            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <!-- <span class="icon flaticon-print"></span> -->
                        <span class="icon flaticon-certificate"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                        <!-- <span class="roadmap-divider"></span> -->
                    </div>
                    <h4>Estampillas Digitales de tiempo </h4>
                    <div class="text">
                    Son un conjunto de características que ayudan 
                    a conocer el momento exacto en que suceden los actos.
                    </div>
                </div>
            </div>

            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <span class="icon flaticon-paper"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                        <!-- <span class="roadmap-divider"></span> -->
                    </div>
                    <h4>Constancias de Conservación de Mensajes de Datos, NOM-151</h4>
                    <div class="text">
                    La NOM-151 establece los requisitos para la 
                    conservación de mensajes de datos, otorgando 
                    integridad a los mismos.
                    </div>
                </div>
            </div>

            <!-- Process BLock -->
            <div class="process-block col-lg-3 col-md-6 col-sm-12">
                <div class="inner-box active">
                    <div class="icon-box">
                        <span class="icon flaticon-ssl-certificate"></span>
                        <span class="count title_ff"><span class="flaticon-check"></span></span>
                        <!-- <span class="count title_ff"><span class="flaticon-check"></span></span> -->
                    </div>
                    <h4>Certificados SSL </h4>
                    <div class="text">
                    Da seguridad a las transferencias de datos, cifrando 
                    la comunicación entre un navegador y un servidor web
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Process Section -->

<!-- Consultation Section -->
<section class="consultation-section">
    <div class="upper-banner" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/3.jpg);">
        <div class="auto-container">
            <div class="sec-title-two light">
                <span class="icon flaticon-inspiration"></span>
                <h3>Conoce más acerca de <br> nuestros servicios.</h3>
                <div class="text">
                Te damos la bienvenida, será un gusto resolver tus dudas.
                <br> ¿Cómo podemos ayudarte?
                </div>
            </div>
        </div>
    </div>

    <!-- Form Container -->
    <div class="form-container">
        <div class="auto-container">
            <form class="form-style-one" action="<?php echo BASE_URL ?>contacto/enviarHome/" method="post">
                <div class="row">
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label>Nombre <sup>*</sup></label>
                        <div class="input-group">
                            <span class="icon fa fa-user"></span>
                            <input type="text" name="nombre" placeholder="Juan" required="">
                        </div>
                    </div>

                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label>Apellido <sup>*</sup></label>
                        <div class="input-group">
                            <span class="icon fa fa-user"></span>
                            <input type="text" name="apellido" placeholder="Hernández" required="">
                        </div>
                    </div>

                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label>Mensaje <sup>*</sup></label>
                        <div class="input-group">
                            <span class="icon fa fa-info"></span>
                            <textarea name="mensaje" id="" cols="30" rows="10"></textarea>
                        </div>
                    </div>

                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label>Número de teléfono <sup>*</sup></label>
                        <div class="input-group">
                            <span class="icon fa fa-phone-volume"></span>
                            <input type="text" name="telefono" placeholder="Numero completo" required="">
                        </div>
                    </div>
                    
                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label>Correo electrónico <sup>*</sup></label>
                        <div class="input-group">
                            <span class="icon fa fa-envelope"></span>
                            <input type="email" name="email" placeholder="nombre@empresa.com" required="">
                        </div>
                    </div>

                    <div class="form-group col-lg-4 col-md-6 col-sm-12">
                        <label></label>
                        <button class="theme-btn btn-style-one" type="submit" name="submit-form">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<!-- End Consultation Section -->

<!-- Testimonials Section -->
<!-- <section class="testimonials-section">
    <div class="container-fluid">
        <div class="sec-title text-center">
            <span class="icon flaticon-user"></span>
            <h3>¿Qué opinan nuestros clientes?</h3>
            <div class="text">
                Hoy en día, las empresas cruzan fronteras y regiones, por lo que necesita un <br> proveedor de servicios que vaya donde usted se encuentre.    
            </div>
        </div>

        <div class="row">
            <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                    <div class="content">
                        <p>
                            Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                        </p>
                        <span class="author">Carlos R.</span>
                    </div>
                </div>
            </div>

            <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                    <div class="content">
                        <p>
                            Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                        </p>
                        <span class="author">Yan A.</span>
                    </div>
                </div>
            </div>

            <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                    <div class="content">
                        <p>
                            Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                        </p>
                        <span class="author">Carlos R.</span>
                    </div>
                </div>
            </div>
            
            <div class="testimonials-block col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <div class="inner-box">
                    <figure class="image"><img src="<?php echo BASE_URL; ?>public/images/resource/testi-thumb-1.jpg" alt=""></figure>
                    <div class="content">
                        <p>
                            Una de las cosas que más me gustan de su empresa, es su seguridad digital.
                        </p>
                        <span class="author">Yan A.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> -->
<!-- End Case Study Section -->

<section class="clients-section">
    <div class="auto-container">
        <div class="sponsors-outer">
            <p style="text-align: center; padding-bottom: 40px; font-size: 18px;">
                Canales autorizados ¿Te interesaría formar parte? 
                Contacta alguno de nuestros canales autorizados o 
                directamente para apoyarte en lo que necesites. 
                <a href="<?php echo BASE_URL; ?>contacto"><b>Contáctanos.</b></a>
            </p>
            <div class="container-aliados">
                <a target="_blank" href="http://www.detecno.com/">
                    <img src="<?php echo BASE_URL; ?>public/images/clients/detecno_hover.png">
                </a>
                <a target="_blank" href="http://www.karalundi.com.mx/esp/">
                    <img src="<?php echo BASE_URL; ?>public/images/clients/karalundi_hover.png">
                </a>
                <a target="_blank" href="https://www.datavision.com.mx/">
                    <img src="<?php echo BASE_URL; ?>public/images/clients/datavision_hover.png">
                </a>
                <a target="_blank" href="https://www.factura1.com.co/">
                    <img src="<?php echo BASE_URL; ?>public/images/clients/factura1.png">
                </a>
            </div>
        </div>
    </div>
</section>

<section class="news-section">
    <div class="auto-container">
        <div class="sec-title text-center">
            <span class="icon flaticon-news"></span>
            <h3>Blog</h3>
            <div class="text">
                Hoy en día, las empresas cruzan fronteras y regiones, por lo que necesita un <br>
                proveedor de servicios que vaya donde usted se encuentre.    
            </div>
        </div>

        <div class="row">
            <?php foreach ($this->noticias as $key => $value) { ?>
            <?php if($key == 3){ break; } ?>
            <div class="news-block col-lg-4 col-md-6 col-sm-12 wow fadeInUp" data-wow-delay="800ms">
                <div class="inner-box">
                    <div class="image-box">
                        <figure class="image">
                            <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?> ">
                                <img src="<?php echo BASE_URL; ?>public/images/noticias/<?php echo $value->getId() ?>.jpg" alt="">
                            </a>
                        </figure>
                        <a href="#" class="date">
                            <i class="far fa-calendar"></i> 
                            <?php echo $value->getFecha()->format('d/m/Y'); ?>
                        </a>
                    </div>
                    <div class="lower-content">
                        <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>" class="read-more">
                            <i class="flaticon-right-arrow"></i>
                        </a>
                        <h4><a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>">
                            <?php if(strlen($value->getTitulo()) <= 50){ ?>
                                <?php echo $value->getTitulo(); ?>    
                            <?php }else{ ?>
                                <?php echo substr($value->getTitulo(),0,50)." ..." ?>
                            <?php } ?>
                        </a></h4>
                        <div class="text">
                            <?php if(strlen($value->getContenido()) <= 300){ ?>
                                <?php echo strip_tags($value->getContenido()); ?>    
                            <?php }else{ ?>
                                <?php echo strip_tags(substr($value->getContenido(),0,300))."..." ?>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>

        <div class="sec-bottom-text">
        PSC World a través de sus servicios de firma digital, genera 
        evidencias e Información que le ayudarán a hacer lo que mejor <br>
        hace, más rápido, más rentable y con mayor certeza jurídica
            <a href="<?php echo BASE_URL; ?>noticias">Leer el blog completo</a>
        </div>
    </div>
</section>

<section class="call-to-action" style="background-image: url(<?php echo BASE_URL; ?>public/images/background/4.jpg);">
    <div class="auto-container">
        <div class="content">
            <div class="sec-title-two">
                <span class="icon flaticon-question-1"></span>
                <h3>Estamos aquí para ayudar</h3>
                <div class="text">Potencia tu empresa con PSC World.</div>
            </div>
            
            <div class="btn-box">
                <a href="<?php echo BASE_URL; ?>contacto" class="theme-btn icon-btn-two">
                    <span>Obtén ayuda aquí</span>
                </a>
            </div>
        </div>
    </div>
</section>