<section class="content-elements" id="page">
        <div class="auto-container">
            <div class="typography">
                <h2>Cumplimiento internacional</h2>
                <div class="">
                    <div class="content-holder">
                        <p>
                            <b>PSCWORLD S.A. DE C.V. </b> 
                        </p>
    
                        <h4>
                            1. México
                        </h4>
                        <div class="cont-cumplimiento-internacional">
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="http://www.diputados.gob.mx/LeyesBiblio/pdf/LFEA.pdf" target="_blank">
                                Ley de Firma Electrónica Avanzada</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="http://www.diputados.gob.mx/LeyesBiblio/pdf_mov/Codigo_de_Comercio.pdf" target="_blank">
                                Código de Comercio</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="http://www.diputados.gob.mx/LeyesBiblio/pdf/125_020719.pdf" target="_blank">
                                Ley Federal del Trabajo (Labor Law)</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="http://www.diputados.gob.mx/LeyesBiblio/pdf/LRITF_090318.pdf" target="_blank">
                                Ley Fintech</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="https://dof.gob.mx/nota_detalle.php?codigo=5478024&fecha=30/03/2017" target="_blank">
                                NOM 151</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="http://dof.gob.mx/nota_detalle.php?codigo=2055516&fecha=31/12/1969" target="_blank">
                                Código Federal de Procedimientos Civiles</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="http://www.diputados.gob.mx/LeyesBiblio/pdf/LFTAIP_270117.pdf" target="_blank">
                                Ley Federal de Transparencia y acceso a la información Pública</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="https://www.dof.gob.mx/nota_detalle.php?codigo=5547774&fecha=09/01/2019" target="_blank">
                                Decreto por el que se reforma el artículo 199 de la Ley del Mercado de Valores</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="https://www.cnbv.gob.mx/Normatividad/Disposiciones%20de%20car%C3%A1cter%20general%20aplicables%20a%20las%20casas%20de%20bolsa.pdf" target="_blank">
                                Disposiciones de Carácter General aplicables de las casas de bolsa</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="https://www.cnbv.gob.mx/Normatividad/Disposiciones%20de%20car%C3%A1cter%20general%20aplicables%20a%20los%20fondos%20de%20inversi%C3%B3n%20y%20a%20las%20personas%20que%20les%20prestan%20servicios.pdf" target="_blank">
                                Disposiciones de Carácter General aplicables a los fondos de inversión y a las personas que les prestan servicios</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="https://dof.gob.mx/nota_detalle.php?codigo=5519300&fecha=13/04/2018" target="_blank">
                                SEP - Títulos escolares digitales</a>
                            </li>
                            <li class="cont-c-i__li">
                                <i class="flaticon-check"></i>
                                <a class="cont-c-i__li--a" href="" target="_blank">
                                SEP - Certificados escolares digitales</a>
                            </li>
                        </div>
                        
                    </div>
                    <h4>
                        2. El Salvador
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.asamblea.gob.sv/decretos/details/166" target="_blank">
                            Ley de Firma Electrónica</a>
                        </li>
                    </div>

                    <h4>
                        3. Costa Rica 
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="http://www.firmadigital.go.cr/Documentos/ley%208454.pdf" target="_blank">
                            Ley Nº 8454: Ley de Certificados, Firmas Digitales y Documentos Electrónicos.</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="http://www.firmadigital.go.cr/Documentos/DecretoNum33018.pdf" target="_blank">
                            Reglamento a la Ley de Certificados, Firmas Digitales y Documentos Electrónicos.</a>
                        </li>
                    </div>

                    <h4>
                        4. Panamá
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.firmaelectronica.gob.pa/documentos/Ley_51-Firma_electronicas_almacenamiento_tecnologico_y_comercio_electronico.pdf" target="_blank">
                            Ley Nº 51 de 22 de julio de 2008.</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.firmaelectronica.gob.pa/documentos/Ley_82-Que_modifica_la_Ley_51_de_2008.pdf" target="_blank">
                            1.2. Ley Nº 82 de 9 de noviembre de 2012.</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.firmaelectronica.gob.pa/documentos/Decreto_684-Que_reglamenta_la_Ley_51_y_82.pdf" target="_blank">
                            Decreto Ejecutivo 684 de 2013.</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.firmaelectronica.gob.pa/documentos/Reglamentacion_Tecnica_1.pdf" target="_blank">
                            Reglamento Técnico No.1 de la Dirección Nacional de Firma Electrónica.</a>
                        </li>
                    </div>

                    <h4>
                        5. Perú
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.minjus.gob.pe/wp-content/uploads/2014/03/Ley27269.pdf" target="_blank">
                            Ley de Firmas y Certificados Digitales.</a>
                        </li>
                    </div>

                    <h4>
                        6. Argentina
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.argentina.gob.ar/firmadigital/normativa" target="_blank">
                            Normatividad de Firma Digital.</a>
                        </li>
                    </div>

                    <h4>
                        7. Estados Unidos
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.fdic.gov/regulations/compliance/manual/10/x-3.1.pdf" target="_blank">
                            The Electronic Signatures in Global and National Commerce Act (E-Sign Act).</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.doi.gov/ocio/policy-mgmt-support/govt-paperwork-elimination-act" target="_blank">
                            Uniform Electronic Transactions Act (UETA).</a>
                        </li>
                    </div>

                    <h4>
                        8. Global
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.uncitral.org/pdf/spanish/texts/general/06-58167_Ebook.pdf" target="_blank">
                            Uncitral: Ley Modelo de la CNUDMI sobre Documentos Transmisibles Electrónicos.</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.uncitral.org/pdf/spanish/texts/electcom/MLETR_ebook_S.pdf" target="_blank">
                            COMISIÓN DE LAS NACIONES UNIDAS PARA EL DERECHO MERCANTIL INTERNACIONAL.</a>
                        </li>
                    </div>

                    <h4>
                        9. Colombia
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.mintic.gov.co/portal/604/articles-3679_documento.pdf" target="_blank">
                            Ley 527 de 1999.</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://tic.bogota.gov.co/node/126" target="_blank">
                            Decreto 1747 de 2000.</a>
                        </li>
                    </div>

                    <h4>
                        10. Chile
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.bcn.cl/leychile/navegar?i=196640&f=2007-11-12&p=" target="_blank">
                            Ley 19799 SOBRE DOCUMENTOS ELECTRONICOS, FIRMA ELECTRONICA Y SERVICIOS DE CERTIFICACIÓN DE DICHA FIRMA.</a>
                        </li>
                    </div>

                    <h4>
                        11. Europa
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://ec.europa.eu/digital-single-market/en/trust-services-and-eid" target="_blank">
                            https://ec.europa.eu/digital-single-market/en/trust-services-and-eid.</a>
                        </li>
                    </div>

                    <h4>
                        12. Guatemala
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="" target="_blank">
                            Ley para el reconocimiento de las comunicaciones y firmas electrónicas decreto 47-2008.</a>
                        </li>
                    </div>

                    <h4>
                        13. Honduras
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="" target="_blank">
                            Ley Sobre Firmas Electrónicas.</a>
                        </li>
                    </div>

                    <h4>
                        14. Paraguay
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="" target="_blank">
                            Ley Nº 4017 / De Validez Jurídica de la Firma Electrónica, la Firma Digital, los Mensajes de Datos y el Expediente Electrónica.</a>
                        </li>
                    </div>

                    <h4>
                        15. Uruguay
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="" target="_blank">
                            Ley Nº 18.600: Documento Electrónico y Firma Electrónica.</a>
                        </li>
                    </div>

                    <h4>
                        16. Brasil
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="http://www.planalto.gov.br/ccivil_03/mpv/Antigas_2001/2200-2.htm" target="_blank">
                            http://www.planalto.gov.br/ccivil_03/mpv/Antigas_2001/2200-2.htm.</a>
                        </li>
                    </div>

                    <h4>
                        17. Canadá
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.ulcc.ca/en/1999-winnipeg-mb/359-civil-section-documents/1138-1999-electronic-commerce-act-annotated" target="_blank">
                            UECA: Uniform Electronic Commerce Act.</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/" target="_blank">
                            PIPEDA: The Personal Information Protection and Electronic Documents Act.</a>
                        </li>
                    </div>

                    <h4>
                        18. India
                    </h4>
                    <div class="cont-cumplimiento-internacional">
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.meity.gov.in/writereaddata/files/Electronic%20signature%20rules%202016.pdf" target="_blank">
                            https://www.meity.gov.in/writereaddata/files/Electronic%20signature%20rules%202016.pdf</a>
                        </li>
                        <li class="cont-c-i__li">
                            <i class="flaticon-check"></i>
                            <a class="cont-c-i__li--a" href="https://www.meity.gov.in/writereaddata/files/The%20Digital%20Signature%20%28End%20entity%29%20Rules%2C%202015.pdf " target="_blank">
                            https://www.meity.gov.in/writereaddata/files/The%20Digital%20Signature%20%28End%20entity%29%20Rules%2C%202015.pdf</a>
                        </li>
                    </div>
                </div>
            </div>
        </div>
    </section>