<section class="contact-form-section">
    <div class="container-login">
        <div class="row form-outer">
            <!-- Form Column -->
            <div class="form-column col-lg-12 col-md-12 col-sm-12">
                <div class="default-form contact-form">
                    <div class="title">
                        <h4>Iniciar Sesión</h4>
                        <p>
                            Por favor ingrese la información para iniciar sesión.
                        </p>
                    </div>

                    <form action="<?php echo BASE_URL ?>login/iniciar/" method="post" id="email-form">
                        <div class="row mid-spacing">
                            <div class="form-group mb-0 col-lg-12">
                                <div class="response"></div>
                            </div>
                            <div class="form-group col-lg-12 col-md-6 col-sm-12">
                                <input type="email" name="email" class="email" placeholder="Correo" required="">
                            </div>

                            <div class="form-group col-lg-12 col-md-6 col-sm-12">
                                <input type="password" name="email" class="pass" placeholder="Contraseña" required="">
                            </div>
                            
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                <button class="theme-btn btn-style-four" type="submit">Entrar</button>
                            </div>
                        </div>
                    </form>
                </div>  
            </div>
        </div>

    </div>
</section>