 <!--Page Title-->
 <section class="page-title" style="background-color: #ffe600; height: 200px;">
        <div class="auto-container">
            <h1>Noticias</h1>
            <!-- <span class="title_divider"></span> -->
        </div>
    </section>
    <!--End Page Title-->

    <!-- News Section -->
    <section class="news-section blog-small-images">
        <div class="auto-container">
            <?php if(!count($this->noticias)){ ?>
                <img class="img-noinfo" src="<?php echo BASE_URL; ?>/public/images/noinfo.png">
            <?php } else{ ?>
            <!-- Blog Checkerboard -->
            <div class="row">
                <!-- News Block -->
                <?php foreach ($this->noticias as $key => $value) { ?>
                <div class="news-block style-two-even">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image">
                                <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>">
                                    <img src="<?php echo BASE_URL; ?>/public/images/noticias/<?php echo $value->getId() ?>.jpg" alt="">
                                </a>
                            </figure>
                            <a href="#" class="date"><i class="far fa-calendar"></i><?php echo $value->getFecha()->format('d/m/Y') ?></a>
                        </div>
                        <div class="lower-content">
                            <h4>
                                <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>">
                                    <?php echo $value->getTitulo(); ?>
                                </a>
                            </h4>
                            <div class="text">
                                <?php echo $value->getContenido(); ?>
                            </div>
                            <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>" class="theme-btn icon-btn-two read-more-btn"><span>Ver más</span></a>
                            <div class="post-info">
                                <div class="post-author">
                                    <img src="<?php echo BASE_URL; ?>/public/images/resource/author-thumb.png" alt="" />
                                    admin
                                </div>

                                <div class="post-option">
                                    <div class="coments_count"><a href="#"><i class="fa fa-comment"></i>0</a></div>
                                    <ul class="social-share">
                                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
            <?php } ?>
        </div>
    </section>