 <!--Page Title-->
 <section class="page-title" style="background-color: #ffe600; height: 200px;">
        <div class="auto-container">
            <h1>Blog</h1>
        </div>
    </section>
    <!--End Page Title-->

    <!-- News Section -->
    <section class="news-section blog-small-images">
        <div class="auto-container">
            <?php if(!count($this->noticias)){ ?>
                <img class="img-noinfo" src="<?php echo BASE_URL; ?>/public/images/noinfo.png">
            <?php } else{ ?>
            <!-- Blog Checkerboard -->
            <div class="row">
                <!-- News Block -->
                <?php foreach ($this->noticias as $key => $value) { ?>
                <div class="news-block style-two-even">
                    <div class="inner-box">
                        <div class="image-box">
                            <figure class="image">
                                <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>">
                                    <img src="<?php echo BASE_URL; ?>/public/images/noticias/<?php echo $value->getId() ?>.jpg" alt="">
                                </a>
                            </figure>
                            <a href="#" class="date"><i class="far fa-calendar"></i><?php echo $value->getFecha()->format('d/m/Y') ?></a>
                        </div>
                        <div class="lower-content">
                            <h4>
                                <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>">
                                <?php echo substr($value->getTitulo(),0,80)."..." ?>
                                </a>
                            </h4>
                            <div class="text">
                                <?php echo strip_tags(substr($value->getContenido(),0,300)."..."); ?>                                
                            </div>
                            <a href="<?php echo BASE_URL; ?>noticias/ver_noticia/<?php echo $value->getId(); ?>" class="theme-btn icon-btn-two read-more-btn"><span>Ver más</span></a>
                            
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
            <?php } ?>
        </div>
    </section>