<section class="container-lista">
    <div class="container-title-lista">
        <div class="container-title-lista__content">
            <span class="icon flaticon-news"></span>
            Lista noticias
        </div>
    </div>

    <article class="container-lista__content">
        <?php if(!count($this->noticias)){ ?>
            <img class="img-noinfo" src="<?php echo BASE_URL; ?>/public/images/noinfo.png">
        <?php } else{ ?>
        <div class="row-lista">
            <div class="column-lista">
                <p>#</p>
            </div>
            <div class="column-lista">
                <p>Título</p>
            </div>
            <div class="column-lista">
                <p>Fecha</p>
            </div>
            <div class="column-lista">
                <p>Descripción</p>
            </div>
            <div class="column-lista">
                <p>Imagen</p>
            </div>
            <div class="column-lista">
                <p>Acciones</p>
            </div>
        </div>
        <?php foreach ($this->noticias as $key => $value) { ?>
        <div class="row-lista">
            <div class="column-lista">
                <p><?php echo $key+1; ?></p>
            </div>
            <div class="column-lista">
                <p><?php echo $value->getTitulo(); ?></p>
            </div>
            <div class="column-lista">
                <p><?php echo $value->getFecha()->format('d/m/Y') ?></p>
            </div>
            <div class="column-lista">
                <p>
                    Se llevo a cabo el desarrollo de 
                    la página de PSC World.
                </p>
            </div>
            <div class="column-lista">
                <div class="box-btn-lista">
                    <a class="btn-lista btn-black" href="<?php echo BASE_URL ?>">
                        <i class="fas fa-image btn-accion"></i>
                    </a>
                </div>  
            </div>
            <div class="column-lista">
                <div class="box-btn-lista">
                    <a class="btn-lista btn-black" href="<?php echo BASE_URL ?>noticias/ver_noticia/<?php echo $value->getId() ?>">
                        <i class="far fa-eye"></i>
                    </a>
                </div>
                <div class="box-btn-lista btn-blue">
                    <a class="btn-lista" href="<?php echo BASE_URL ?>noticias/editar/<?php echo $value->getId() ?>">
                        <i class="far fa-edit"></i>
                    </a>
                </div>
                <div class="box-btn-lista btn-rojo">
                    <a class="btn-lista" href="<?php echo BASE_URL ?>noticias/eliminar/<?php echo $value->getId() ?>">
                        <i class="far fa-trash-alt"></i> 
                    </a>
                </div>
            </div>
        </div>
        <?php } ?>
        <?php } ?>
    </article>
</section>