<section class="checkout-page" style="padding-top: 30px;">
    <div class="auto-container">
        <div class="coupen-outer">
            <div class="upper-box">
                <div class="text"><span class="icon flaticon-news"></span> Lista noticias</div>
            </div>
            
        </div>

        <div class="col-sm-12">
            <div class="hstb-pricing-table-holder">
                <div class="hstb-table">
                    <div class="row thead">
                        <div class="col-xs-2 th">#</div>
                        <div class="col-xs-2 th">Titulo</div>
                        <div class="col-xs-2 th">Fecha</div>
                        <div class="col-xs-2 th">Descripción</div>
                        <div class="col-xs-2 th">Imagen</div>
                        <div class="col-xs-2 th">Acciones</div>
                    </div>
                    <?php foreach ($this->noticias as $key => $value) { ?>
                    <div class="row trow">
                        <div class="col-xs-2 td"><?php echo $key+1; ?></div>
                        <div class="col-xs-2 td"><?php echo $value->getTitulo(); ?></div>
                        <div class="col-xs-2 td"><?php echo $value->getFecha()->format('d/m/Y') ?></div>
                        <div class="col-xs-2 td">
                            Se llevo a cabo el desarrollo de 
                            la página de PSC World.
                        </div>
                        <div class="col-xs-2 td">
                            <a href="post.html"><i class="fas fa-image btn-accion"></i></a>
                        </div>
                        <div class="col-xs-2 td">
                            <!-- <a class="register-button" href="#">Register</a> -->
                            <a href="post.html"><i class="far fa-eye btn-accion"></i></a>
                            <a href=""><i class="far fa-edit  btn-accion"></i></a>
                            <a href=""><i class="far fa-trash-alt  btn-accion btn-rojo "></i> </a>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>