<div class="sidebar-page-container right-sidebar" style="padding-top: 30px">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Content Side-->
                <div class="content-side col-lg-8 col-md-12 col-sm-12">
                    <div class="blog-post hover-stop">
                        <!-- News Block -->
                        <div class="news-block">
                            <div class="inner-box">
                                <div class="image-box">
                                    <figure class="image"><img src="<?php echo BASE_URL; ?>/public/images/noticias/<?php echo $this->noticia->getId() ?>.jpg" alt=""></figure>
                                    <a href="#" class="date"><i class="far fa-calendar"></i> <?php echo $this->noticia->getFecha()->format('d/m/Y') ?></a>
                                </div>
                                <div class="lower-content">
                                    <?php echo $this->noticia->getContenido() ?>
                                    <!-- <p>
                                        El Lorem Ipsum fue concebido como un texto de relleno, formateado de una cierta manera para permitir la presentación de elementos gráficos en documentos, sin necesidad de una copia formal. El uso de Lorem Ipsum permite a los diseñadores reunir los diseños y la forma del contenido antes de que el contenido se haya creado, dando al diseño y al proceso de producción más libertad.
                                    </p>
                                    <p>
                                        Se cree ampliamente que la historia de Lorem Ipsum se origina con Cicerón en el siglo I aC y su texto De Finibus bonorum et malorum. Esta obra filosófica, también conocida como En los extremos del bien y del mal, se dividió en cinco libros. El Lorem Ipsum que conocemos hoy se deriva de partes del primer libro Liber Primus y su discusión sobre el hedonismo, cuyas palabras habían sido alteradas, añadidas y eliminadas para convertirlas en un latín sin sentido e impropio. No se sabe exactamente cuándo el texto recibió su forma tradicional actual. Sin embargo, las referencias a la frase "Lorem Ipsum" se pueden encontrar en la Edición de la Biblioteca Clásica Loeb de 1914 del De Finibus en las secciones 32 y 33. Fue en esta edición del De Finibus en la que H. Rackman tradujo el texto. El siguiente fragmento se selecciona de la sección 32:
                                    </p>
                                    <p>
                                        Pasando a la década de 1960, el Lorem Ipsum fue popularizado por el fabricante de tipografía Letraset, que lo utilizó en sus campañas publicitarias. Letraset ofrecía páginas de Lorem Ipsum como hojas de transferencia, que fueron ampliamente utilizadas en la era anterior a los ordenadores para los diseños. Estas páginas de transferencia, conocidas como Letraset Body Type, se incluyeron en la publicidad de la compañía y en su popular catálogo.
                                    </p>
                                    <div class="two-column row">
                                        <figure class="column col-lg-6 col-md-6 col-sm-12">
                                            <a href="<?php echo BASE_URL; ?>/public/images/resource/post-img-1.jpg" class="lightbox-image"><img src="<?php echo BASE_URL; ?>/public/images/resource/post-img-1.jpg" alt=""></a>
                                        </figure>
                                        <figure class="column col-lg-6 col-md-6 col-sm-12">
                                            <a href="<?php echo BASE_URL; ?>/public/images/resource/post-img-2.jpg" class="lightbox-image"><img src="<?php echo BASE_URL; ?>/public/images/resource/post-img-2.jpg" alt=""></a>
                                        </figure>
                                    </div>
                                    <p>
                                        El Lorem Ipsum fue reintroducido en la década de 1980 por Aldus Corporation, una empresa que desarrolló Software de Publicación de Escritorio. Su producto más conocido PageMaker viene con gráficos y plantillas de procesamiento de textos previamente instaladas que contienen una versión del lenguaje latín falso.
                                    </p> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Sidebar Side-->
                <div class="sidebar-side sticky-container col-lg-4 col-md-12 col-sm-12">
                    <aside class="sidebar theiaStickySidebar">
                        <div class="sticky-sidebar">

                            <!-- Newslatters-->
                            <div class="sidebar-widget newslatters">
                                <div class="sidebar-title"><h3><span class="icon flaticon-rss-symbol"></span>Boletin informativo</h3></div>
                                <div class="text">
                                    Ingrese su dirección de correo electrónico a 
                                    continuación para suscribirse.
                                </div>
                                <form method="post" action="blog-sidebar.html">
                                    <div class="form-group">
                                        <input type="text" name="input" value="" placeholder="Correo electrónico" required="">
                                        <button type="submit" class="theme-btn"><span class="btn-title">Suscribir</span></button>
                                    </div>
                                </form>
                            </div>
         
                            <!-- Latest News -->
                            <div class="sidebar-widget latest-news">
                                <div class="sidebar-title"><h3>Noticias recientes</h3></div>
                                <div class="widget-content">
                                    <article class="post">
                                        <figure class="thumb"><img src="<?php echo BASE_URL; ?>/public/images/resource/post-thumb-1.jpg" alt=""></figure>
                                        <h5>Fuerza laboral</h5>
                                        <div class="post-info">Sep 09 2020</div>
                                        <a href="<?php echo BASE_URL; ?>noticias/ver_noticia" class="overlay-link"></a>
                                    </article>

                                    <article class="post">
                                        <figure class="thumb"><img src="<?php echo BASE_URL; ?>/public/images/resource/post-thumb-2.jpg" alt=""></figure>
                                        <h5>Una llamada para ti</h5>
                                        <div class="post-info">Sep 09 2020</div>
                                        <a href="<?php echo BASE_URL; ?>noticias/ver_noticia" class="overlay-link"></a>
                                    </article>

                                    <article class="post">
                                        <figure class="thumb"><img src="<?php echo BASE_URL; ?>/public/images/resource/post-thumb-3.jpg" alt=""></figure>
                                        <h5>Compromiso en nuestro equipo</h5>
                                        <div class="post-info">Sep 09 2020</div>
                                        <a href="<?php echo BASE_URL; ?>noticias/ver_noticia" class="overlay-link"></a>
                                    </article>
                                </div>
                            </div>

                            <!-- Tags -->
                            <div class="sidebar-widgets">
                                <div class="widget-content">
                                    <div class="banner-box-one" style="background: url(<?php echo BASE_URL; ?>/public/images/publicidad.jpg);">
                                        <div class="content">
                                            <h5 class="title">Spot publicitario</h5>
                                            <p>Enfrentar desafíos en el proceso de trabajo es muy</p>
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </div>