<div class="modalimg" style="visibility: hidden;">
    <div class="modal__content modalimg__content">
        <div class="box-modalimg box-modalimg-noticias">
        <?php foreach ($this->banners as $key => $value) { ?>
            <img class="imagenDModal-noticias" src="<?php echo BASE_URL; ?>/public/images/banners/<?php echo $value->getId() ?>.jpg" alt="">
            <i class="fas fa-times-circle cerrarimg"></i>
        </div>
        <?php } ?>
    </div>
</div>

<section class="container-lista">
    <div class="container-title-lista">
        <div class="container-title-lista__content">
            <div>
                <span class="icon flaticon-news"></span>
                Lista noticias
            </div>
            <a href="<?php echo BASE_URL ?>banner/registrar" class="theme-btn btn-style-four btn-amarillo-oscuro">Registrar</a>
        </div>
    </div>

    <article class="container-lista__content">
    <?php if(!count($this->banners)){ ?>
            <img class="img-noinfo" src="<?php echo BASE_URL; ?>/public/images/noinfo.png">
        <?php } else{ ?>
        <div class="row-lista">
            <div class="column-lista">
                <p>#</p>
            </div>
            <div class="column-lista">
                <p>Título</p>
            </div>
            <div class="column-lista">
                <p>URL</p>
            </div>
            <div class="column-lista">
                <p>Fecha</p>
            </div>
            <div class="column-lista">
                <p>Imagen</p>
            </div>
            <div class="column-lista">
                <p>Acciones</p>
            </div>
        </div>
        <?php foreach ($this->banners as $key => $value) { ?>
        <div class="row-lista">
            <div class="column-lista">
                <p><?php echo $key+1; ?></p>
            </div>
            <div class="column-lista">
                <p><?php echo $value->getTitulo(); ?></p>
            </div>
            <div class="column-lista">
                <p>
                    <?php echo substr($value->getUrl(),0,20)."..." ?>
                </p>
            </div>
            <div class="column-lista">
                <p><?php echo $value->getFecha()->format('d/m/Y') ?></p>
            </div>

            <div class="column-lista">
                <div class="box-btn-lista">
                    <a class="abririmg btn-lista btn-black" href="<?php echo BASE_URL ?>">
                        <i class="fas fa-image btn-accion"></i>
                    </a>
                </div>
            </div>
           
            <div class="column-lista">
                <div class="box-btn-lista">
                    <a class="btn-lista btn-black" href="<?php echo BASE_URL ?>banners/ver_noticia/<?php echo $value->getId() ?>">
                        <i class="far fa-eye"></i>
                    </a>
                </div>
                <div class="box-btn-lista btn-blue">
                    <a class="btn-lista" href="<?php echo BASE_URL ?>banner/editar/<?php echo $value->getId() ?>">
                        <i class="far fa-edit"></i>
                    </a>
                </div>
                <div class="box-btn-lista btn-rojo">
                    <a class="btn-lista" href="<?php echo BASE_URL ?>banner/eliminar/<?php echo $value->getId() ?>">
                        <i class="far fa-trash-alt"></i> 
                    </a>
                </div>
            </div>
        </div>
        <?php } ?>
        <?php } ?>
    </article>
</section>