<section class="page-title" 
style="background-image: url(<?php echo BASE_URL; ?>/public/images/doc2signBanner.jpg); height: 200px;">    
</section>

<section class="services-section style-two">
    <div class="auto-container">
        <div class="row">
            <!-- Text column -->
            <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                <div class="inner-column">            
                    <div class="sec-title">
                        <span class="sub-title">Doc2sign</span>
                        <h3>
                            PSC World presenta <br>
                            Doc2sing
                        </h3>
                        <div class="text">
                            <strong>
                                Donde podras firmar a distancia y de forma digital documentos de cualquier tipo desde laborales hasta mercantiles y civiles.
                            </strong>
                        </div>
                    </div>
                    <p>
                        Estarás siempre en cumplimiento de las disposiciones aplicables vigentes, teniendo la seguridad en que el documento firmado será legalmente vinculante.
                    </p>
                    <a href="<?php echo BASE_URL; ?>contacto" class="theme-btn icon-btn-two">
                        <span>Contactar</span>
                    </a>
                </div>
            </div>

            <!-- Image Column -->
            <video preload="none" autoplay="autoplay" loop="loop" controls="controls" class="image-column col-lg-7 col-md-12 col-sm-12" src="<?php echo BASE_URL; ?>/public/images/doc2sign.mp4"></video>
        </div>
    </div>
</section>
<section class="fluid-section-two">
    <div class="container-fluid">
        <div class="row no-gutters">
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <!-- <span class="sub-title">innovations</span> -->
                        <h3>
                            Doc2Sign se adapta <br> a tus necesidades
                        </h3>
                        <div class="text">
                            <b>Doc2Sign Avalúos</b> esta es una solución para Unidades de Valuación
                            o integradores que necesiten realizar operaciones firmado de Avalúos 
                            o implementar la entrega hacia sociedad hipotecaria federal
                            desde Doc2Sign.
                            <br><br>
                            <b>Doc2Sign nóminas</b> esta es una solución que sirve casi para cualquier 
                            empresa que requiera que sus empleados firmen sus recibos
                            de nómina; pues con esta plataforma lo pueden hacer 
                            virtualmente teniendo la validez legal necesaria para 
                            cualquier tipo de querella.
                        </div>
                    </div>
                </div>
            </div>

            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/tablet.jpg);"></div>
        </div>
    </div>
</section>

<section class="services-section style-two">
    <div class="auto-container">
        <div class="row">
            <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                <div class="inner-column">            
                    <div class="sec-title">
                        <h3>
                            Proceso Multidisciplinario
                        </h3>
                        <div class="text">
                            <strong>
                            Cuando hablamos de la firma digital de un contrato ya no solamente estamos hablando del impacto que conlleva para el área jurídica, ya es una tarea de distintas áreas:
                            </strong>
                        </div>
                    </div>
                    <ul class="list-style-one">
                        <li>
                            El equipo laboral necesita ser más eficiente en el trato con los colaboradores, generar ahorros y ofrecer una mejor experiencia a los involucrados.
                        </li>
                        <li>
                            El equipo laboral necesita firmar de nuevo los contratos laborales para permitir una libre afiliación a un Sindicado a los trabajadores.
                        </li>
                        <li>El equipo comercial necesita vender más por lo que necesita ser más eficiente de cara a los cierres.</li>
                        <li>
                            El equipo de compras quiere tener firmados más rápidamente los contratos que mandan a sus proveedores, localizarlos más rápido y dar una una mejor experiencia a las partes.
                        </li>
                        <li>
                            El equipo fiscal quiere que exista un contrato firmado digital con su respectiva NOM 151 y estampilla de tiempo para tener una fecha cierta sobre el documento.
                        </li>
                    </ul>
                    
                    <a href="<?php echo BASE_URL; ?>contacto" class="theme-btn icon-btn-two">
                        <span>Contactar</span>
                    </a>
                </div>
            </div>

            <div class="image-column col-lg-7 col-md-12 col-sm-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/womanComputer.jpg);"></div>            
        </div>
    </div>
</section>

<section class="fluid-section-four">
    <div class="auto-container">
        <div class="row">
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <h3>
                            Firma con tu voz o <br> 
                            con tu huella dactilar
                        </h3>
                        <div class="text">
                            Todos los procesos de firma digital pudieran robustecerse más allá de un NIP o una firma digital autógrafa, ya que pudieran estar acompañados de un factor biométrico como lo sería: voz, dactilar o facial. Para lo cual hemos visto dos corrientes:
                        </div>
                    </div>
                    <ul class="list-style-one">
                        <li>
                            Entolamiento de un biométrico previo a firma.
                        </li>
                        <li>
                            Solicitud de un biométrico al momento de la firma.
                        </li>
                    </ul>
                </div>
            </div>

            <div class="image-column col-lg-6 col-md-12">
                <div class="image-layer" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/18.jpg);"></div>
            </div>
        </div>
    </div>
</section>
<section class="fluid-section-two">
    <div class="container-fluid">
        <div class="row no-gutters">
            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/marcoRegulatorio.jpg);"></div>

            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <!-- <span class="sub-title">innovations</span> -->
                        <h3>
                            Cumplimos con el<br>
                            Marco Regulatorio
                        </h3>
                        <ul class="list-style-one">
                            <li>
                                Ley de Firma Electrónica Avanzada. 
                            </li>
                            <li>
                                Código de Comercio.
                            </li>
                            <li>Código Federal de Procedimientos Civiles.</li>
                            <li>Código Civil Federal.</li>
                            <li>Ley Federal del Trabajo (Art. 776 y 836a, 836b y 836c).</li>
                            <li>Ley Federal de transparencia y acceso a la información pública gubernamental.</li>
                            <li>Ley Fintech</li>
                            <li>Decreto por el que se reforma el artículo 199 de la Ley del Mercado de Valores</li>
                            <li>Disposiciones de Carácter General aplicables de las casas de bolsa</li>
                            <li>Disposiciones de Carácter General aplicables a los fondos de inversión y alas personas que les prestan servicios</li>
                            <li>Secretaría de Educación Pública</li>
                            <li>Entre otras...</li>
                        </ul>
                    </div>
                </div>
            </div>  
        </div>
    </div>
</section>

<section class="fluid-section-four">
    <div class="auto-container">
        <div class="row">
            <!-- Content Column -->
            <div class="content-column col-lg-6 col-md-12 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <h3>
                            Servicio Asincróno 
                        </h3>
                        <div class="text">
                            Este es el servicio que vimos con Doc2Sign, en donde nos 
                            mandan el documento, los firmantes, el orden, etc y a partir 
                            de allí detonamos las alertas por correo y gestionamos las 
                            firmas, permitiendo a su sistema estar preguntando el estatus 
                            de las firmas (Pendiente, Parcial, firmado), tendrán acceso a 
                            la interfaz <a href="https://www.doc2sign.com/" target="_blank">www.doc2sign.com</a> tanto ustedes como quienes sean 
                            invitados a firmar, el documento firmado tendrán la NOM 151 con 
                            su respectiva estampilla de tiempo.
                        </div>
                    </div>
                </div>
            </div>

            <!-- Image COlumn -->
            <div class="image-column col-lg-6 col-md-12">
                <div class="image-layer" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/asincrono.jpg);"></div>
            </div>
        </div>
    </div>
</section>

<section class="services-section style-two">
    <div class="auto-container">
        <div class="row">

            <div class="image-column col-lg-7 col-md-12 col-sm-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/cumplimientoInternacional.jpg);"></div>
            <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                <div class="inner-column">            
                    <div class="sec-title">
                        <h3>
                            Cumplimiento internacional
                        </h3>
                        <div class="text">
                            Doc2sign cumple con Normativas de carácter internacional y en los diversos sectores de aplicación para el uso de la firma electrónica. Dichos cumplimientos son con base en el siguiente marco normativo. 
                        </div>
                    </div>
                    <a href="<?php echo BASE_URL; ?>cumplimientoInternacional" class="theme-btn icon-btn-two">
                        <span>Ver más</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="contact-form-section">
    <div class="auto-container">
        <div class="row form-outer">
            <!-- Image Column -->
            <div class="image-column col-lg-6 col-md-12 col-sm-12">
                <div class="layer-image" style="background-image: url(<?php echo BASE_URL; ?>public/images/doc2signINFO.jpg);"></div>
            </div>

            
            <div class="form-column col-lg-6 col-md-12 col-sm-12">
                <div class="default-form contact-form">
                    <div class="title">
                        <h4>Firma Electrónica <br> Avanzada (FEA)</h4>
                        <p>
                        En estos últimos meses por el COVID el tema de firma digital ha cobrado mucha fuerza, esto por los ahorros, la eficiencia, mejoramiento de tiempos, y ahora desde perspectiva fiscal; detonado por la Jurisprudencia relacionada a la Fecha Cierta en Documentos privados en donde ahora el SAT buscar no hacer deducciones de contratos que no tengan una fecha cierta, proceso que en medios digitales se obtiene con la incorporación de de la NOM 151, proceso que hace nuestro sistema Doc2sign.
                        <br><br> En pocas palabras con <b>doc2sign</b>, además de tener el total respaldo de nuestra acreditación como PSC (Prestador de Servicios de Certificación), podrás firmar vía web <a href="https://doc2sign.com">https://doc2sign.com</a>, vía nuestras APPs en IOS y Android o bien vía nuestros conectores (proceso sincróno y asincróno), esto además de poder configurar de acuerdo al tipo de documento que estás firmando el realizar firmas digitales de acuerdo a la forma que más se adapte a tus necesidades;  podrás firmar con tu FIEL (eFirma) del SAT, con una firma digital autógrafa o bien con un NIP, teniendo el respaldo el Código de Comercio en su Artículo 89, de la Ley de Firma Electrónica Avanzada, la Ley Federal del Trabajo, la Ley Fintech, Norma 151 y muchas más.

                        </p>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</section>