<section class="page-title" 
style="background-image: url(<?php echo BASE_URL; ?>/public/images/doc2signBanner.jpg); height: 200px;">    
</section>

<section class="services-section style-two">
        <div class="auto-container">
            <div class="row">
                <!-- Text column -->
                <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                    <div class="inner-column">            
                        <div class="sec-title">
                            <span class="sub-title">Doc2sign</span>
                            <h3>
                                PSC World presenta <br>
                                Doc2sing
                            </h3>
                            <div class="text">
                                <strong>
                                    Donde podras firmar a distancia y de forma digital documentos de cualquier tipo desde laborales hasta mercantiles y civiles.
                                </strong>
                            </div>
                        </div>
                        <p>
                            Estarás siempre en cumplimiento de las disposiciones aplicables vigentes, teniendo la seguridad en que el documento firmado será legalmente vinculante.
                        </p>
                        <a href="<?php echo BASE_URL; ?>contacto/index" class="theme-btn icon-btn-two">
                            <span>Contactar</span>
                        </a>
                    </div>
                </div>

                <!-- Image Column -->
                <div class="image-column col-lg-7 col-md-12 col-sm-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/womanComputer.jpg);"></div>
            </div>
        </div>
    </section>
    <section class="fluid-section-two">
        <div class="container-fluid">
            <div class="row no-gutters">
                <!-- Content Column -->
                <div class="content-column col-lg-6 col-md-12 col-sm-12">
                    <div class="inner-column">
                        <div class="sec-title">
                            <!-- <span class="sub-title">innovations</span> -->
                            <h3>
                                Doc2Sign se adapta <br> a tus necesidades
                            </h3>
                            <div class="text">
                                <b>Doc2Sign Avalúos</b> esta es una solución para Unidades de Valuación
                                o integradores que necesiten realizar operaciones firmado de Avalúos 
                                o implementar la entrega hacia sociedad hipotecaria federal
                                desde Doc2Sign.
                                <br><br>
                                <b>Doc2Sign nóminas</b> esta es una solución que sirve casi para cualquier 
                                empresa que requiera que sus empleados firmen sus recibos
                                de nómina; pues con esta plataforma lo pueden hacer 
                                virtualmente teniendo la validez legal necesaria para 
                                cualquier tipo de querella.
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Image COlumn -->
                <div class="image-column col-lg-6 col-md-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/tablet.jpg);"></div>
            </div>
        </div>
    </section>
    <section class="services-section style-two">
        <div class="auto-container">
            <div class="row">
                <!-- Text column -->
                <div class="text-column col-lg-5 col-md-12 col-sm-12 order-2">
                    <div class="inner-column">            
                        <div class="sec-title">
                            <span class="sub-title">Contratos inteligentes</span>
                            <h3>
                                Autosign
                            </h3>
                            <div class="text">
                                <strong>
                                    Un contrato inteligente (Smart contract), es un programa informático que permite ejecutar acuerdos registrados entre dos o más partes, es el testigo que ante cierto resultado ejecutará de forma automática ciertas reglas o acciones predefinidas.
                                </strong>
                            </div>
                        </div>
                        <p>
                            Es un programa no controlado por las partes o sus agentes y que ejecuta un contrato automático, el cual funciona como una sentencia if-then (si-entonces) de cualquier otro programa de ordenador. <br><br>
                            Con la diferencia de que se realiza de una manera que interactúa con activos reales.
                        </p>
                        
                        <a href="<?php echo BASE_URL; ?>contacto/index" class="theme-btn icon-btn-two">
                            <span>Contactar</span>
                        </a>
                    </div>
                </div>

                <!-- Image Column -->
                <div class="image-column col-lg-7 col-md-12 col-sm-12" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/contrato.jpg);"></div>
            </div>
        </div>
    </section>
    <section class="fluid-section-four">
        <div class="auto-container">
            <div class="row">
                <!-- Content Column -->
                <div class="content-column col-lg-6 col-md-12 col-sm-12">
                    <div class="inner-column">
                        <div class="sec-title">
                            <h3>
                                Firma con tu voz o <br> 
                                con tu huella dactilar
                            </h3>
                            <div class="text">
                                Todos los procesos de firma digital pudieran robustecerse más allá de un NIP o una firma digital autógrafa, ya que pudieran estar acompañados de un factor biométrico como lo sería: voz, dactilar o facial. Para lo cual hemos visto dos corrientes:
                            </div>
                        </div>
                        <ul class="list-style-one">
                            <li>
                                Entolamiento de un biométrico previo a firma.
                            </li>
                            <li>
                                Solicitud de un biométrico al momento de la firma.
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Image COlumn -->
                <div class="image-column col-lg-6 col-md-12">
                    <div class="image-layer" style="background-image: url(<?php echo BASE_URL; ?>/public/images/background/18.jpg);"></div>
                </div>
            </div>
        </div>
    </section>